### ISSUE TITLE
Remove GIL to avoid deadlocks when calling CEF functions 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#102]
In the pxd file, function needs to be defined as "nogil". In the pyx file the call must use the "with nogil" statement.

From [Cython's documentation](http://docs.cython.org/src/userguide/external_C_code.html#acquiring-and-releasing-the-gil):

> Note that acquiring the GIL is a blocking thread-synchronising operation, and therefore potentially costly. It might not be worth releasing the GIL for minor calculations. Usually, I/O operations and substantial computations in parallel code will benefit from it.

Revision ec1ce788373b removes the GIL lock from the following calls: Initialize(), Shutdown(), CreateBrowserSync(), SetOsModalLoop(), QuitMessageLoop(), CefExecuteProcess().

Keeping this issue Open, as there still might be some functions from which the GIL lock should also be removed.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 8 Jan 2014 at 11:15

**Comment by cztomczak** [comment]
Add GIL section to Contributing-code.md document in commit a5d97f0.
