### ISSUE TITLE
Remove big binary files from git history

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#103]
In the past, Windows binary files were kept in the git repository and it grown significantly by now to 200 MB. Big files need to be found (dll, exe, pak, lib) and removed.

Big files can be removed after migrating to GitHub: https://help.github.com/articles/remove-sensitive-data/ . After it's done users need to rebase any branches they have created:

> Tell your collaborators to rebase, not merge, any branches they created off of your old (tainted) repository history. One merge commit could reintroduce some or all of the tainted history that you just went to the trouble of purging.

OLD INFO: I've tried instructions here:  http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects . As of that time I couldn't push such changes back to Google Code online repo. One solution proposed here: http://stackoverflow.com/a/11277470/623622 is to recreate the repository. But this will most probably break existing cloned repositories.

Binaries files and extensions:
```
.exe .dll .pdb .so .pyd .dylib .dat .bin
"cefclient", "subprocess"
.pak
.lib .a  .o .obj
```

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 8 Jan 2014 at 4:50
* Blocking: #117

**Comment by cztomczak** [comment]
Repo history has been cleaned of binary files. Repo size before changes: **340 MB**. After changes: **4 MB**.

BFG Repo-Cleaner commands executed:
```
git clone --mirror ...
make a backup ...
java -jar bfg.jar --delete-files cefclient cefpython.git
java -jar bfg.jar --delete-files subprocess cefpython.git
java -jar bfg.jar --delete-files '*.{exe,dll,pdb,so,pyd,dylib,dat,bin,pak,lib,a,o,obj}' cefpython.git
cd cefpython.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
```
