### ISSUE TITLE
Update Cython to latest

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#110]
A thorough testing will be required, as version 0.20 breaks some things. While 
doing a quick testing, one issue was found so far.
## Issue with strings

The Debug() function needs to accept both unicode and bytes strings. In version 0.19.2 of Cython you could pass unicode string and it was converted automatically, but with the new version an error is throwed:

```
 TypeError: Expected str, got unicode
```

The Debug() function:
https://code.google.com/p/cefpython/source/browse/cefpython/utils.pyx?r=2f6f611c2fcf#20

Called from CreateJavascriptCallback():
https://code.google.com/p/cefpython/source/browse/cefpython/javascript_callback_cef3.pyx?r=2f6f611c2fcf

The functionName param was decoded from the cefpython IPC message using the json library, and the json library automatically converted the string to unicode.

There might be more places where unicode is passed and it would throw an error.

**Comment by cztomczak** [comment]
Updated to Cython 0.24.1 in commit 6f0d9b3af1ff4569266ca9d0cb5319e922597ff4. The issue with strings is not yet fixed in all places (eg. Debug func), further testing is required. Tested only with hello_world.py example.

**Comment by cztomczak** [comment]
Updated to Cython 0.25.2 with no problems.

**Comment by cztomczak** [comment]
See https://github.com/cztomczak/cefpython/issues/250 for future updates.
