### ISSUE TITLE
Add support for OnFullscreenModeChange callback

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#120]
I've submitted a patch to add an OnFullscreenModeChange callback to CEF
http://code.google.com/p/chromiumembedded/issues/detail?id=562#c16

This is the corresponding patch for cefpython, in the hope that Marshall 
accepts my patch or some variation of it.

Original issue reported on code.google.com by `finn.hug...@gmail.com` on 28 Mar 2014 at 12:58

Attachments:
- [cefpython-fullscreen.patch](https://storage.googleapis.com/google-code-attachments/cefpython/issue-120/comment-0/cefpython-fullscreen.patch)

**Comment by cztomczak** [comment]
Further work on this will happen in Issue #281.
