### ISSUE TITLE
Fix HTTPS cache problems on pages with certificate errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#125]
This is an optional fix. By default Chromium disables caching when there is certificate error. This patch will fix the HTTPS caching only when ApplicationSettings "ignore_certificate_errors" is set to True.

See http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11609

The patch suggested in the linked topic works fine after making some minor 
changes.

```
Index: net/http/http_cache_transaction.cc
===================================================================
--- http_cache_transaction.cc   (revision 241641)
+++ http_cache_transaction.cc   (working copy)
@@ -2240,7 +2240,8 @@
   // reverse-map the cert status to a net error and replay the net error.
   if ((cache_->mode() != RECORD &&
        response_.headers->HasHeaderValue("cache-control", "no-store")) ||
-      net::IsCertStatusError(response_.ssl_info.cert_status)) {
+       (!cache_->GetSession()->params().ignore_certificate_errors &&
+       net::IsCertStatusError(response_.ssl_info.cert_status))) {
     DoneWritingToEntry(false);
     ReportCacheActionFinish();
     if (net_log_.IsLoggingAllEvents())
```

The patch was verified to work with CEF 3 branch 1650 revision 1646. The https 
web server was nginx running on Ubuntu.

Patch instructions [available here](https://github.com/cztomczak/cefpython/wiki/BuildOnLinux#fix-https-caching-on-sites-with-ssl-certificate-errors-optional) (both BuildOnLinux and BuildOnWindows wiki pages).

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 27 May 2014 at 8:38

**Comment by cztomczak** [comment]
Looks like this patch won't work anymore with latest CEF. In this [CEF topic](https://magpcss.org/ceforum/viewtopic.php?f=6&t=14900) it was reported that the ignore_certificate_errors setting doesn't work with self-signed certificates. This feature was initially intended for sites with self-signed certificates.

**Comment by cztomczak** [comment]
This patch is currently disabled in v55 on Windows/Mac. Only Linux has this applied.

**Comment by cztomczak** [comment]
This patch is now be disabled by default since v66 release. See commit f87422b. We plan on using Spotify builds on Linux and all platforms and this patch was not accepted into upstream. API docs and migration guide doc were updated.

**Comment by cztomczak** [comment]
Maintaining such patch is costly, so it will be disabled unless there are parties interested in having this enabled in official releases.

**Comment by cztomczak** [comment]
Keeping this Open and labelling KB.
