### ISSUE TITLE
CefInitialize fails intermittently on Linux during launch of a subprocess

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#131]
Observed in branch 1650 when running the wx.chromectrl sample2.py example. 
Reported here:
http://www.magpcss.org/ceforum/viewtopic.php?p=22227#p22227

It might be an edge case, as there is something wrong with the sample2.py 
example. The wx controls eat 100% CPU all the time. The crash wasn't yet 
observed in any of the other examples.

There is an issue in the CEF Issue Tracker for stress testing application 
launching to detech and fix such problems:
https://code.google.com/p/chromiumembedded/issues/detail?id=1207

Similar problem occured in CEF2go on Linux and OSX:
https://github.com/CzarekTomczak/cef2go/issues/8

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 1 Aug 2014 at 2:38

**Comment by cztomczak** [comment]
Check if this is still an issue after update to Chrome 47.

**Comment by cztomczak** [comment]
I haven't noticed this issue anymore with CEF Python 51/53.
