### ISSUE TITLE
Remove libudev symlink when CEFPython updates to Chrome 41

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#148]
See code in "setup.py" and "debian.postinst" files. 

Dependency on specific version of libudev library was removed in upstream Chromium. This change is planned to ship in Chrome 41, which should happen in a month or two. See Chromium Issue #415212 comment #18: https://code.google.com/p/chromium/issues/detail?id=415212#c18 .

See also issue #105 which added libudev symlink.

**Comment by cztomczak** [comment]
Fixed in commit 22ade5c5196f14d6fadf362b3ef3e8eeadbfa2de
