### ISSUE TITLE
Documentation improvements (TOC, remove depracted CEF 1, restructure)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#150]
Tasks:
* [x] Generate TOC using DocToc - create tools/doctoc.py that will call doctoc for all .md files in docs/, but will skip these containing a comment: `<!-- SKIP doctoc -->`. This tool will display a list of files that changed (doctoc when run on a directory lists all that were processed).
* [x] Remove CEF 1 documentation

See also:
* #211 "Make documentation searchable using GitHub's code search"
* #201 "Migrate wiki pages from the "wiki" branch to the Wiki tab" - some ideas for improvements were commented there.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 6 Dec 2014 at 10:18

**Comment by cztomczak** [comment]
In the wiki Tab you can create a sidebar that will appear on the right side of all wiki pages. I think the content from the API wiki page could go to such sidebar. Basically it will add categories and replace the All Pages sidebar. The default Pages list sidebar will probably be hidden by default after custom sidebar is added.

**Comment by cztomczak** [comment]
Attaching script for fixing markdown docs.
[fix_markdown.zip](https://github.com/cztomczak/cefpython/files/152344/fix_markdown.zip)
