### ISSUE TITLE
Latest CEF does not support VS2008 anymore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#153]
Python 2.7 libraries can be build only with VS2008. When buildingg 
libcef_dll_wrapper with latest CEF, some issue may occur that will require 
fixes. See the related issue in the CEF tracker: 
https://code.google.com/p/chromiumembedded/issues/detail?id=1471

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 15 Dec 2014 at 5:49

**Comment by cztomczak** [comment]
This is fixed by copying stdint.h - see docs/Build-instructions.md the Requirements section.
