### ISSUE TITLE
Build CEF on Mac without the tcmalloc memory allocator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#155]
Currently builds for Mac are with tcmalloc global hook enabled. This means that the CEF Python library needs to be imported the very first before any other libraries like for example wxPython.

There was a similar tcmalloc issue for Linux, see Issue #73 for details.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 9 Jan 2015 at 12:11

**Comment by cztomczak** [comment]
tcmalloc is not used on OS X, at least not in the latest releases. See: https://chromium.googlesource.com/chromium/src/+/79a9c7f8

**Comment by cztomczak** [comment]
Both Spotify builds and the automate.py tool build CEF without tcmalloc. So the next release will have this fixed. Any deprecated comments in examples about tcmalloc will be removed as part of works on Issue #207.
