### ISSUE TITLE
Cookies not flushed to disk when closing app immediately in wxpython.py (Linux yet to fix)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#158]
```
Noticed this behavior after setting the "cache_path" option in the wxpython.py 
example (it also required setting path in the GetCookieManager callback).

Cookies are flushed to disk only after about 30 seconds. If app is closed 
before that, cookies do not persist.

This is similar to a recent issue I've reported for the PHP Desktop project: 
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12357
```

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 11 Jan 2015 at 2:15

**Comment by cztomczak** [comment]
In v50+ there was code added in cefpython.pyx that makes sure that shutdown executes cleanly and if not an "ERROR" message is displayed and logged to debug.log. Even if shutdown is not clean, in such case the code in cefpython.pyx will try to force close browsers, give it some time to close and only then shutdown. So far all works good.
