### ISSUE TITLE
Create a simple wxPython example - wxsimple.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#160]
This example should be similar to what we have for other GUIs: PyQt, PySide - just basic embedding. Current wxpython.py example may overwhelm at first look.

Make this example to run on all platforms by checking platform.system() to execute platform specific code. See Issue #159 for a list of differences for various platforms.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 11 Jan 2015 at 5:07

**Comment by cztomczak** [comment]
Duplicate of #269.
