### ISSUE TITLE
The default en-US locale pak file fails to load on Mac

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#163]
There is an error: "locale.file_path empty":

```
[0605/180015:WARNING:resource_bundle.cc(269)] locale_file_path.empty()
[0605/180015:FATAL:main_delegate.cc(449)] Check failed: !loaded_locale.empty(). Locale could not be found for en-US
```

What is causing the issue is that in Mac binaries the Resources/en-US.lproj/ directory is missing. Only on Windows and Linux there is an "en-US.pak" file. The solution for Mac is to set locale to "en" using the `--locale_pak=Resources/en.lproj/locale.pak` flag using [CommandLineSwitches](https://github.com/cztomczak/cefpython/blob/master/api/CommandLineSwitches.md). Example code below:

```
g_switches = {
        "locale_pak": cefpython.GetModuleDirectory()
            +"/Resources/en.lproj/locale.pak"
}
cefpython.Initialize(g_applicationSettings, g_switches)
```

I wonder if this error might have something to do with the fact that we're not using the directory structures like the one found in cefclient.app. CEF libraries are in the "Chromium Embedded Framework.framework" directory with Libraries/Resources subdirectories. I've put all libraries/executables in a single directory to make it consistent with how it's done on Windows and Linux. Also to avoid possible issues with app packagers like pyinstaller.

The corresponding issue reported on the CEF Forum: 
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12569

Marshall responded:

```
    Chromium code makes assumptions about the app bundle structure to find locale 
    files. If you don't have the expected structure then it fails.
```

TODO: let's get rid of the --locale_pak flag and use ApplicationSettings.lang 
option instead. Set the "en" lang by default in cefpython.Initialize(). Remove 
the --locale_pak switch from wxpython.py and chromectrl.py.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 14 Jan 2015 at 8:11

**Comment by rgerman** [comment]
Hey, I have the same issue when trying to run pygtk_.py in OSX 10.10.

I tried with the --lang=en and lang=en-GB, but it still shows me the error

`[0323/182548:FATAL:main_delegate.cc(449)] Check failed: !loaded_locale.empty(). Locale could not be found for en`

**Comment by cztomczak** [comment]
@rgerman Ask questions on the Forum.

**Comment by cztomczak** [comment]
@rgerman Ask questions and report problems on the Forum.

**Comment by cztomczak** [comment]
Recheck in v55.

**Comment by cztomczak** [comment]
Not an issue anymore in v56 release.
