### ISSUE TITLE
Examples crash on Mac when app doesn't have permission to write to the debug.log file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#164]
When using preinstalled Python that ships with OS X and after install the 
cefpython3 package there are problems with running examples from the 
/Library/Python/2.6/site-packages/cefpython3/examples directory. App has no 
permission to write to the debug.log file and it results in Python crash with 
"Segmentation fault: 11" error. In the console you can see warnings like this:
```
    [CEF Python] WARNING: failed writing to debug file: debug.log
```
These warnings are not the cause of the crash. I think that it is CEF that 
causes the crash when it can't access the debug.log file.

Try this: in the examples check if app has permission to write to debug.log 
file and if not then set the ApplicationSettings.log_file to an empty string.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 14 Jan 2015 at 7:00

**Comment by cztomczak** [comment]
Do not run examples from the package directory. Copy them elsewhere, or best clone cefpython repository and use the latest code.
