### ISSUE TITLE
Python Wheels - DESCRIPTION.rst UNKNOWN

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#166]
How to make this file be filled with information about package? I suspect that this would result in package information being automatically updated on PyPI when making a new release. Currently when making a new release all fields are cleared and need to be filled again, because PyPI expects this information to be embedded in the .whl file.

Update: This data can be supplied in setup.py, see all fields:
https://docs.python.org/2/distutils/setupscript.html#additional-meta-data

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 17 Jan 2015 at 1:27

**Comment by cztomczak** [comment]
Fixed in 	cfd4912.
