### ISSUE TITLE
Create "chrome31" branch and an archive 31.2 release before updating to a newer CEF

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#172]
Create the branch only after CEF 1 code path was removed (Issue 106). Make sure 
there are no CEF 1 binaries left. Also make sure that there aren't any CEF 3 
binary files. The var/ directory is 1.21 MB, maybe remove some files from there.

* Blocked on: #178

**Comment by cztomczak** [comment]
Removing CEF 1 code path might break things, so leaving as is. CEF 1 binaries removed (Issue #103). An archive 31.2 release is ready: https://github.com/cztomczak/cefpython/releases/tag/v31.2 .New branch "cefpython31" created.
