### ISSUE TITLE
Restructure directories (binaries, installer, libraries) to allow for git branching

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#178]
Thanks to Kevin Lawrence for the idea. Pasting email contents below:

--------------------------------------------------------------------

I think I understand the problem though. During build setup you put all of your 
library/binary files in cef3/[os]/ setup/binaries. If you switch branches those 
binary files would cause issues. Maybe you just need to namespace things then?

Have a directory structure like this:

cef3/[os]/build/[branch]/

Where [branch] contains the directories:
32
    - binary
    - installer
    - library
64
    -binary
    -installer
    - library

Make it so the build directory never gets committed in the .gitignore. Maybe 
you could update your command script to create the above directory structure 
for a given name and copy all of the install files/demo files in to their 
appropriate places. Something like:

compile.bat -make test, which would create a directory cef3/[os]/build/test/ 
with the above directories. Then you could fill in those directories with the 
appropriate files automatically.

This would allow you to keep the directories across branches and keep from 
committing them to the repository.

* Blocking: #172

**Comment by cztomczak** [comment]
Not a priority now I think. Closing. I will re-visit this idea when there is a need to maintain more than one branch at the same time.
