### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by laravelbook** [cztomczak/cefpython#183]
cefpython should provide support for Python 3.5

**Comment by cztomczak** [comment]
Experimental Python 3 support was added in commit 6f0d9b3af1ff4569266ca9d0cb5319e922597ff4.

Tested with Python 3.5.2 as well and works fine with the hello_world.py example running on Linux.

**Comment by cztomczak** [comment]
Python 3 beta release for Linux: https://github.com/cztomczak/cefpython/releases/tag/v53.1

**Comment by cztomczak** [comment]
Any further updates for both Python 3.4 and 3.5 will occur in Issue #121.
