### ISSUE TITLE
wxPython (Phoenix) just hangs

### ISSUE THREAD

**Issue by ssbb** [cztomczak/cefpython#189]
Hi! Got it working with 3.0.2 wxPython, but the same version of Phoenix (not Classic) does not work. Any plans to support it? Thanks!

**Comment by cztomczak** [comment]
What Phoenix version, OS and CEF?

**Comment by ssbb** [comment]
Thanks for quick reply! :+1: 

OS: OS X El Capitan (10.11.2)
WX version: 3.0.3.dev1836+f764b32 osx-cocoa (phoenix)
CEF version: cefpython3 31.2 (from pypi)

**Comment by cztomczak** [comment]
Can you provide logs from console?

**Comment by cztomczak** [comment]
If the problem reproduces with latest version the isssue can be reopened.
