### ISSUE TITLE
Migrate wiki pages from the "wiki" branch to the Wiki tab

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#201]
Anyone can edit wiki pages.

The "wiki" branch:
https://github.com/cztomczak/cefpython/tree/wiki

The Wiki tab:
https://github.com/cztomczak/cefpython/wiki

See also Issue #150 - to improve wiki pages (adding TOC, removing CEF 1 docs).

**Comment by jegger** [comment]
Do you know if the wiki branch is linked to the wiki tab?
I suspect that the branch was just created by the google-code exporter but does not really mater for github, as the wiki has it's own repository (https://github.com/cztomczak/cefpython.wiki.git).

But actually that is just a guess. Does anyone know?

**Comment by cztomczak** [comment]
No, the wiki branch is a different thing.

I've been playing a bit with wiki pages on GH last few days. I want to add table of contents using doctoc (see here: https://github.com/cztomczak/phpdesktop/wiki/Chrome-settings) and get rid of camel case for pages names (BuildOnWindows --> Build on Windows).

When copying page from the wiki branch to the wiki tab internal links become broken.

**Comment by cztomczak** [comment]
The syntax of wikis exported by Google Code is of low quality. There are many html tags being used when it could have been replaced with native markdown syntax. Examples are lists `<li>` and line breaks `<br>` (unnecessary because GFM [github flavored markdown] supports automatic line breaks for paragraphs).

**Comment by jegger** [comment]
Okay, I started working on transforming the wiki. At least fixing link's and images. I did not touch the content yet. Actually I'm currently working on it right now...
https://github.com/rentouch/cefpython/wiki
https://github.com/rentouch/cefpython.wiki.git

**Comment by cztomczak** [comment]
Thanks Dominique. I will definitely want to make it more readable and get rid of CEF 1 deprecated content, but the most important for now is to just have these wiki pages working in the wiki tab.

For functions/options I think the H3 header should be used, H2 is too big. H2 may be used to categorize functions/options on some pages.

**Comment by cztomczak** [comment]
I've added you to Collaborators, that should give you push access to the wiki repository.

**Comment by jegger** [comment]
In VersionNumbering: CEF versions consist of...?
What is the new schematic? branch-name+commit hash?

**Comment by jegger** [comment]
I just pushed my changes to this wiki repository. What I tried so far:
- Fixing links to issues in cefpython and cef
- Fixing links to files in cefpython and cef
- Fixing links to wiki pages in cefpython and cef
- Fixing source url to images (created a images/ folder in the wiki-repository)

**Comment by cztomczak** [comment]
CEF version: 3.2526.1366.g8617e7c - CEF 3 + branch + git commit count + git revision (short hash). Not entirely sure about 1366 git commit count, but looks like it when viewing releases on cefbuilds.com.

Took a quick look at wiki, looks GOOD! I see that settings/functions are already linkable (H3), so adding TOC will be easy. Not sure what to do about the Home wiki page, it duplicates what is already in README.

**Comment by cztomczak** [comment]
Yes, it's commit number, from include/cef_version.h:
```
#define CEF_VERSION "3.2526.1366.g8617e7c"
#define CEF_VERSION_MAJOR 3
#define CEF_COMMIT_NUMBER 1366
#define CEF_COMMIT_HASH "8617e7c22c1215e26aff2a594bb1165b8972b9b1"
#define COPYRIGHT_YEAR 2016
```

**Comment by cztomczak** [comment]
I see on the Home wiki page that Issue 121 is linked this way:
`[Issue 121](https://github.com/cztomczak/cefpython/issues/121)`
On GH you can also use relative links like this:
`[Issue #121](../../issues/121)` - already used this way in README.md.
This also applies for linking to code.

**Comment by cztomczak** [comment]
But when linking from wiki/ it would be `../issues/121` (`../` only once). Just for your information, I don't think it's an issue now.

**Comment by jegger** [comment]
I replaced the absolute paths to the issues and source now. Makes sense, didn't know that this was possible.

**Comment by jegger** [comment]
Regarding the README / Home(of wiki): I would prefer to let the README stay as it is but change the home page in the wiki to something like an API overview and links to the build instructions / downloads (even the idea to have it on the right side makes sense too). I guess I just think of something less general and more developer-specific on the wiki home page.

**Comment by cztomczak** [comment]
Thanks. 

Okay, so API page would become Home with added links to Build/Downloads wiki pages (and possibly other pages if not included eg. InternalDevelopment).

Regarding the sidebar - I think listing all wiki pages there is not a good idea, there are too many of them. Maybe let's add a few categories in the sidebar that link to Home # H2 headers:
 * Downloads - link to Home#Downloads
 * Development - link to Home#Development - BuildOnXxx, .., Internal Development
 * API search - link to Home#API-search
 * Examples - link to Home#Examples
 * Modules - ...
 * Settings - ...
 * Classes and objects - ...
 * Client handlers - ...

That would be nice I think, a small sidebar with categories for all wiki pages.

**Comment by cztomczak** [comment]
I did the improvements mentioned in previous post - see the new Home wiki page and the Sidebar.

**Comment by jegger** [comment]
Good job, looks great to me. I think the wiki is on a usable state now.

**Comment by cztomczak** [comment]
More improvements to the Home page and sidebar. Also created seperate API and Help wiki pages.

I will close this issue after all wiki pages have been verified and will delete the wiki branch.
