### ISSUE TITLE
Test on Windows XP

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#206]
Use Microsoft's free virtual machines:
https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by bernizt** [comment]
The provided link does not contain a download to a Windows XP virtual machine. I could do some tests on a Windows XP sp3 32 bits, if required (running on Parallels).

**Comment by cztomczak** [comment]
Windows XP is no more supported with latest CEF.
