### ISSUE TITLE
expose CreateBrowser in API

### ISSUE THREAD

**Issue by stefanbacon** [cztomczak/cefpython#225]
Would it be possible to expose CreateBrowser as well as CreateBrowserSync?
This would allow headless operation.

I was a bit at a loss as to how convert a python ClientHandler to C++ so as to have callbacks set though.

**Comment by stefanbacon** [comment]
actually got it working without any UI frameworks here's a gist:
https://gist.github.com/stefanbacon/7b1571d57aee54aa9f8e9021b4848d06

**Comment by cztomczak** [comment]
Nice! Added link to your example here: https://github.com/cztomczak/cefpython/blob/master/api/RenderHandler.md
