### ISSUE TITLE
are there any demo which could show how to interacts python with  jscript 

### ISSUE THREAD

**Issue by lion117** [cztomczak/cefpython#226]
![demo](http://www.codeproject.com/KB/cs/990346/image005.gif)

[cefsharp demo](http://www.codeproject.com/Articles/990346/Using-HTML-as-UI-Elements-in-a-WinForms-Applicatio)

**Comment by cztomczak** [comment]
See the wxpython.py example: https://github.com/cztomczak/cefpython/wiki/wxPython
Ask questions on the Forum.
