### ISSUE TITLE
PyQt / PySide - browser control does not resize on Linux

### ISSUE THREAD

**Issue by mmolero** [cztomczak/cefpython#234]
First it all, It is a huge work you've done here, thanks for sharing.

I've tested the cefpython embedded in a PySide Appplication on Windows. It goes great!!!
However, When I want to use it on Linux (changing now the Q11EmbedContainer as you showed in the linux examples) I noticed that this version is not able to resize the CEF Browser along with the MainFrame. Is there any way to do that?

I just know Qt so I dont know how one can get the required resize methods using the gtkPlugPtr.
Thanks in advance!!

**Comment by cztomczak** [comment]
PySide was not tested on Linux. Have you looked at the PyQt example on Linux - does resizing work there? See: https://github.com/cztomczak/cefpython/blob/cefpython31/cefpython/cef3/linux/binaries_64bit/pyqt.py

In cefpython 51 (master) there is an additional method Browser.SetBounds (implemented on Linux only) to set window bounds during resize events. New beta release for Linux will appear soon.

**Comment by mmolero** [comment]
Thanks for quick response.  With pyqt happens the same.

So if I compile the master from source I might use the method you mentioned right?

**Comment by cztomczak** [comment]
I've put quick build instructions for CEF Python 51 BETA in docs/Build-instructions.md. Usage of Browser.SetBounds() is in the pygtk_.py example. If you have problems building ask on the forum or just wait a few days for the release.

**Comment by mmolero** [comment]
Thanks again for you quick reply. For sure I wait for the next release

**Comment by mmolero** [comment]
Using the CEFPython 51 now I was able to execute successfully on PyQt. Based on your guideline: 

```python
class MainFrame(QX11EmbedContainer):
    browser = None
    def __init__(self, parent=None):
    super(MainFrame, self).__init__(parent)
        self.x = 0
	self.y = 0
	self.width = 600
	self.height = 600 
             
        windowInfo = cefpython.WindowInfo()
        windowInfo.SetAsChild(int(self.winId()),[0,0,800,600])
        
        self.browser = cefpython.CreateBrowserSync(windowInfo,
                browserSettings={},
                navigateUrl= "http://www.google.com") 
        self.show()

    def moveEvent(self, event):
	pos = event.pos()
        self.x = pos.x()
        self.y = pos.y() 
        self.browser.SetBounds(self.x, self.y, self.width, self.height)
         
    def resizeEvent(self, event):
	size = event.size()
        self.width = size.width()
        self.height = size.height() 
        self.browser.SetBounds(self.x, self.y, self.width, self.height)
```

**Comment by cztomczak** [comment]
Great.
Let's keep this issue Open, as it's still not fixed for both PySide/PyQt in sources.

Btw. I've just updated build instructions for CEF Python 51 BETA - you can use prebuilt binaries from GH releases which have the ICU error fixed. (unless you already use them)

**Comment by mmolero** [comment]
The following code works using PyQt/PySide and the last pre-release of CEF Python 51 Beta  on Linux:

```python

import sys
from cefpython3 import cefpython

from PySide.QtGui import *
from PySide.QtCore import *
#from PyQt4.QtGui import *
#from PyQt4.QtCore import *


class MainWindow(QMainWindow):
    mainFrame = None

    def __init__(self):
        super(MainWindow, self).__init__(None)
       
        self.mainFrame = MainFrame(self)
        self.setCentralWidget(self.mainFrame)
        self.resize(1000, 1000)
        self.setFocusPolicy(Qt.StrongFocus)

    def focusInEvent(self, event):
        pass
        
    def closeEvent(self, event):
        self.mainFrame.browser.CloseBrowser()

class MainFrame(QX11EmbedContainer):
    browser = None

    def __init__(self, parent=None):
        super(MainFrame, self).__init__(parent)
        self.x = 0
        self.y = 0
        self.width = 600
        self.height = 600 
        windowInfo = cefpython.WindowInfo()
        windowInfo.SetAsChild(int(self.winId()),[self.x, self.y, self.width,self.height])
        
        self.browser = cefpython.CreateBrowserSync(windowInfo,
                browserSettings={},
                navigateUrl= "http://www.google.com") 
        self.show()

    def moveEvent(self, event):
        pos = event.pos()
        self.x = pos.x()
        self.y = pos.y() 
        self.browser.SetBounds(self.x, self.y, self.width, self.height)
          

    def resizeEvent(self, event):
        size = event.size()
        self.width = size.width()
        self.height = size.height() 
        self.browser.SetBounds(self.x, self.y, self.width, self.height)
       
        

class CefApplication(QApplication):	
    timer = None
    
    def __init__(self, args):
        super(CefApplication, self).__init__(args)
        self.createTimer()
 	
    def createTimer(self):
		self.timer = QTimer()
		self.timer.timeout.connect(self.onTimer)  		
		self.timer.start(10)
    
    def onTimer(self):
        # The proper way of doing message loop should be:
        # 1. In createTimer() call self.timer.start(0)
        # 2. In onTimer() call MessageLoopWork() only when
        #    QtGui.QApplication.instance()->hasPendingEvents() returns False.
        # But... there is a bug in Qt, hasPendingEvents() returns always true.
		cefpython.MessageLoopWork()

    def stopTimer(self):
        # Stop the timer after Qt message loop ended, calls to MessageLoopWork()
        # should not happen anymore.
        self.timer.stop()

if __name__ == '__main__':


    settings = {}
  
    # This directories must be set on Linux
    settings["locales_dir_path"]  = cefpython.GetModuleDirectory()+"/locales"
    settings["resources_dir_path"] = cefpython.GetModuleDirectory()

  
    settings["context_menu"] = {
      "enabled": True,
      "navigation": True, # Back, Forward, Reload
      "print": False,
      "view_source": False,
      "external_browser": False, # Open in external browser
      "devtools": False, # Developer Tools
    }
    settings["browser_subprocess_path"] = "%s/%s" % (cefpython.GetModuleDirectory(), "subprocess")

    
    cefpython.Initialize(settings)
    app = CefApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    app.exec_()
    app.stopTimer()

    # Need to destroy QApplication(), otherwise Shutdown() fails.
    # Unset main window also just to be safe.
    del mainWindow
    del app

    cefpython.Shutdown()
``` 

Thanks

**Comment by cztomczak** [comment]
Thanks, that is helpful. I will merge it soon when I work on Issue #207 (Create examples/ root dir - simplify and unify examples to work on all platforms).

**Comment by cztomczak** [comment]
You are missing a call to WindowUtils.InstallX11ErrorHandlers() - later you may run into X11 non-fatal errors that will crash your app if you don't install error handlers.

Also you should probably call Browser.NotifyMoveOrResized during resize/move events. Try opening mouse context menu and then move window while it is still open to see. More details in docs: https://github.com/cztomczak/cefpython/blob/master/docs/api/Browser.md#notifymoveorresizestarted

**Comment by cztomczak** [comment]
Try opening a popup window - without X11 error handler installed it will probably crash app (it did in Kivy example).

**Comment by mmolero** [comment]
Ok thanks
So should one call WindowUtils.InstallX11ErrorHandlers() before or after the initialization? 
Because in the example of kivy was before but in the example of pygtk was after.

**Comment by cztomczak** [comment]
X11 error handlers must be installed before you create any windows - that's when X11 errors can occur, when interacting with windows. In upstream CEF doc comment only states that handlers must be installed after initializing GTK. In the cefclient example handlers are installed after a call to CefInitialize(), so looks like it is safe to do so: https://bitbucket.org/chromiumembedded/cef/src/05ee60b7b4704f5e763b65d2a1fbea83815b34ac/tests/cefclient/cefclient_gtk.cc?at=master&fileviewer=file-view-default#cefclient_gtk.cc-110

**Comment by mmolero** [comment]
Ok Thanks for the info :+1:

**Comment by cztomczak** [comment]
Added qt.py example in commit 24418ec.
