### ISSUE TITLE
Python 3.? support

### ISSUE THREAD

**Issue by mese79** [cztomczak/cefpython#239]
Hi
I really appreciate your efforts for this project. for me it's so much fun to develop my python applications with html5 UI!
But as i read issues i thought the new beta release should work with python 3. is this right?
Cause i could not run examples of `cefpython3-51.0` with `python 3.5.1`:
> Exception: Unsupported python version: 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0]

So i'm waiting for python 3 news! cause it's a pain to work with python 2 and unicode strings.
Thanks again.

**Comment by cztomczak** [comment]
Issue #121 is still Open.
