### ISSUE TITLE
Mac error: failed to execvp: subprocess EH.app [SOLVED by disabling plugins]

### ISSUE THREAD

**Issue by mmolero** [cztomczak/cefpython#242]
You can find an example using CEFPython and PySide for Linux, Windows, and OSX: https://gist.github.com/mmolero/c3db18390aa71bb6b3cdcb9822483032

Now it works well on Linux, Ubuntu 14.04 64 Bits (CEFPython 51) and Windows 10 64 Bits (CEFPython 31.2). However it does not work on OSX, 10.11 El Capitan (CEFPython 31.2) yet.

Do you know why? Any Idea
Thanks!!!

**Comment by cztomczak** [comment]
What is the error? Anything interesting in debug.log file? Have you run the wxpython.py example that is distributed with Mac binaries, does it work?

**Comment by mmolero** [comment]
No I did not test the wxpython example yet, only the pyside example shown in the gist

In Windows and Linux work perfectly but in OSX the following error appears:

```
2016-07-07 15:00:00.789 python[2555:502512] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2016-07-07 15:00:00.991 subprocess[2558:502690] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2016-07-07 15:00:03.760 subprocess[2559:503084] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
```

The resulting window is:

![screen shot 2016-07-07 at 15 44 55](https://cloud.githubusercontent.com/assets/3868004/16655222/acfcc718-4459-11e6-93e8-f31dc072abbd.png)

Although the window appears, it is not able to show all the web content. Also it has the issue concerning the resizing.

**Comment by mmolero** [comment]
The debug.log contains the following:

```
[CEF Python] Initialize() called
[CEF Python] CefExecuteProcess(): exitCode = -1
[CEF Python] CefInitialize()
[CEF Python] App_OnBeforeCommandLineProcessing_BrowserProcess()
[CEF Python] App: Command line string for the browser process:  --browser-subprocess-path=/anaconda/lib/python2.7/site-packages/cefpython3/subprocess --lang=en-US --resources-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/Resources --locales-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/locales --remote-debugging-port=65402 --no-sandbox --locale_pak=/anaconda/lib/python2.7/site-packages/cefpython3/Resources/en.lproj/locale.pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] Switch already set, ignoring: locale_pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] WindowUtils::IsWindowHandle() not implemented (always True)
[CEF Python] CreateBrowserSync() called
[CEF Python] navigateUrl: http://www.google.com
[CEF Python] CefBrowser::CreateBrowserSync()
[CEF Python] GetPyBrowser(): creating new PyBrowser, browserId=1
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] CefBrowser::CreateBrowserSync() succeeded
[CEF Python] SendProcessMessage(): message=DoJavascriptBindings, arguments size=1
[CEF Python] App: Command line string for the renderer process: /anaconda/lib/python2.7/site-packages/cefpython3/subprocess --type=renderer --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/locales --resources-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/Resources --locale_pak=/anaconda/lib/python2.7/site-packages/cefpython3/Resources/en.lproj/locale.pak --disable-accelerated-video-decode --channel=2722.1.577725080
[CEF Python] App: Renderer: OnProcessMessageReceived(): DoJavascriptBindings
[CEF Python] App: Renderer: OnContextCreated()
[CEF Python] App: Renderer: DoJavascriptBindingsForFrame(): bindings are set
[CEF Python] App: Browser: OnProcessMessageReceived(): OnContextCreated
[CEF Python] V8ContextHandler_OnContextCreated()
[CEF Python] App: Renderer: DoJavascriptBindingsForFrame(): bindings are set
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
```
in the terminal appears the following when debug:True:

```
[CEF Python] Initialize() called
[CEF Python] CefExecuteProcess(): exitCode = -1
[CEF Python] CefInitialize()
2016-07-07 15:57:32.640 python[2733:609921] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[CEF Python] App_OnBeforeCommandLineProcessing_BrowserProcess()
[CEF Python] Command line string for the browser process:  --browser-subprocess-path=/anaconda/lib/python2.7/site-packages/cefpython3/subprocess --lang=en-US --resources-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/Resources --locales-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/locales --remote-debugging-port=63978 --no-sandbox --locale_pak=/anaconda/lib/python2.7/site-packages/cefpython3/Resources/en.lproj/locale.pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] Switch already set, ignoring: locale_pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] WindowUtils::IsWindowHandle() not implemented (always True)
[CEF Python] CreateBrowserSync() called
[CEF Python] navigateUrl: http://www.google.com
[CEF Python] CefBrowser::CreateBrowserSync()
[CEF Python] GetPyBrowser(): creating new PyBrowser, browserId=1
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] CefBrowser::CreateBrowserSync() succeeded
[CEF Python] SendProcessMessage(): message=DoJavascriptBindings, arguments size=1
2016-07-07 15:57:35.662 subprocess[2736:610142] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2016-07-07 15:57:35.710 subprocess[2737:610147] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[CEF Python] Command line string for the renderer process: /anaconda/lib/python2.7/site-packages/cefpython3/subprocess --type=renderer --no-sandbox --lang=en-US --lang=en-US --locales-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/locales --resources-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/Resources --locale_pak=/anaconda/lib/python2.7/site-packages/cefpython3/Resources/en.lproj/locale.pak --disable-accelerated-video-decode --channel=2733.1.1760050128
[CEF Python] Renderer: OnProcessMessageReceived(): DoJavascriptBindings
[CEF Python] Renderer: OnContextCreated()
[CEF Python] Renderer: DoJavascriptBindingsForFrame(): bindings are set
[CEF Python] Browser: OnProcessMessageReceived(): OnContextCreated
[CEF Python] V8ContextHandler_OnContextCreated()
[CEF Python] Renderer: DoJavascriptBindingsForFrame(): bindings are set
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH

```

**Comment by cztomczak** [comment]
> LaunchProcess: failed to execvp:
> /anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH

This error means that it failed to launch the subprocess executable. Check execute permissions on the subprocess executable whether it has chmod +x and while at it check permissions for other files as well.

How did you install cefpython on Mac? It doesn't seem you've installed it using official instructions, what is subprocess doing in /anaconda/lib/? See the Download_CEF3_Mac wiki page.

It is best to ask questions on the Forum. Create an issue in the tracker only when you are sure this is a bug in CEF / CEF Python.

**Comment by cztomczak** [comment]
Strange thing is that once in logs you can see this path for the subprocess, which is correct:
> /anaconda/lib/python2.7/site-packages/cefpython3/subprocess

And then error shows a different path:
> /anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH

**Comment by mmolero** [comment]
I installed it using 
```
pip install cefpython3
```

Indeed I followed the official instructions, https://github.com/cztomczak/cefpython/wiki/Download_CEF3_Mac#install-from-pypi

And subprocess does have the executable mode (-rwxr-xr-x). 

If I do a print from cefpython.GetModuleDirectory() appears  */anaconda/lib/python2.7/site-packages/cefpyton3*

**Comment by mmolero** [comment]
You're right, it seems strange.

**Comment by cztomczak** [comment]
There was a similar issue with permissions when using preinstalled Python, see the note here about debug.log permissions: https://github.com/cztomczak/cefpython/wiki/Download_CEF3_Mac#examples

The setup.py installer will set chmod on files, but it needs permissions. On the Download_CEF3_Mac page, in the "Install from PyPI" section there is a note to install using sudo:

> When using preinstalled Python that ships with OS X, to install pip type "sudo easy_install pip" and 
> to install the cefpython3 package type "sudo pip install cefpython3".

Looks like this also applies when using Anaconda Python.

**Comment by cztomczak** [comment]
*Looks like this may also apply when using Anaconda Python. Try installing using "sudo pip install cefpython3".

**Comment by cztomczak** [comment]
Run cefclient and wxpython.py, theese are available in the directory where the package was installed - see if they work correctly.

**Comment by mmolero** [comment]
Cefclient (script?) is not in the cefpython folder, where can I find it?

**Comment by cztomczak** [comment]
cefclient wasn't included on Mac, but you can download TestApp and copy the cefclient executable to the cefpython3 directory: https://cefbuilds.com/#branch_1650

**Comment by cztomczak** [comment]
But after a second thought it might not work, because the structure of directories is different in cefpython.

**Comment by cztomczak** [comment]
Looks like the structure of dirs/files might have something to do with the issue. In cefpython on Mac we didn't use the official structuring from CEF. In cefclient the subprocess executable is named "cefclient Helper" and there are three kinds of it in the "cefclient.app/Contents/Frameworks" directory:

* cefclient Helper.app
* cefclient Helper EH.app
* cefclient Helper NP.app

This is the same executable, but duplicated in two different directories with the "EH" and "NP" postsfixes - I'm not sure what these are supposed to mean. In cefpython there is only one helper - the subproces executable. But the error and its path "/anaconda/lib/subprocess EH.app" suggests that the subprocess expects the .app folder structure. It expects that the helper app has such structure:

> cefclient Helper EH.app/Contents/MacOS

But instead the helper is here:

> /anaconda/lib/python2.7/site-packages/cefpython3/subprocess

So it does "../../../" to go out of the  "cefclient Helper EH.app/", but as we don't follow the official app structure, it ends up doing:

> /anaconda/lib/python2.7/site-packages/cefpython3/../../../ cefclient Helper EH.app/...

which becomes:

> /anaconda/lib/cefclient Helper EH.app/...

To resolve the issue it needs to be investigated why it looks for these helpers: ".. EH.app" and ".. NP.app". During my testing on Mac I've never had this issue, it always used only the default subprocess executable. What do the EH and NP names mean? It has some meaning for sure. Maybe this could be fixed by providing some flag/setting, so that it uses the default helper app.

**Comment by mmolero** [comment]
FYI, the CefClient App works when it was executed from the cepython folder

**Comment by cztomczak** [comment]
Found this: https://bugs.chromium.org/p/chromium/issues/detail?id=520680
> Google Chrome Helper EH.app is the "executable helper" which is only used by NPAPI.

What if you disable all plugins? Then it shouldn't use this EH helper. You can disable plugins with the BrowserSettings.disable_plugins option: https://github.com/cztomczak/cefpython/blob/master/api/BrowserSettings.md#plugins_disabled

**Comment by cztomczak** [comment]
Looks like this will no more be an issue with newer CEF 51+:

> On OS X, there are currently Google Chrome Helper EH.app and
> Google Chrome Helper NP.app, which are no longer used with the deprecation
> of NPAPI. This changes removes the helpers, both from the build process,
> and any code referring to them.

**Comment by cztomczak** [comment]
A second and ugly solution:
1. Create empty directories: /anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
2. Copy the subprocess executable to that .../MacOS directory and rename it to "subprocess EH"

**Comment by mmolero** [comment]
When I disable the plugins disappear the errors:
```
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
LaunchProcess: failed to execvp:
/anaconda/lib/subprocess EH.app/Contents/MacOS/subprocess EH
```

However, the web content of google does not appear as it should be (same window as the above screenshot)

**Comment by cztomczak** [comment]
Copying the subprocess executable won't work, because it expects libcef.so in current directory - however you could experiment by copying also .so file.

Check the new debug.log file with the plugins disabled - any new warnings/errors?

**Comment by cztomczak** [comment]
Try loading a different url, or a local .html file (file:///home/user/...).

**Comment by cztomczak** [comment]
Test the wxpython.py example located in site-packages/cefpython3/examples/.

**Comment by mmolero** [comment]
For example loading www.apple.com, it seems it works, however the problem of window resizing remains.  I dont know what components the google website uses because just appears the buttom toolbar.

**Comment by mmolero** [comment]
Are you going to release the Cefpython 51 for OSX soon? The Cefpython 51 for linux works excellent.

**Comment by cztomczak** [comment]
Application logic differs on Mac - see the wxpython.py example distributed with Mac binaries. The message loop and shutdown work differently on mac (and may be some other differencies), see the wxpython.py example for reference. 

This issue is fixed by disabling plugins. Any more questions please ask on the Forum, as they seem off-topic now. The title of this issue was changed: "LaunchProcess: failed to execvp: subprocess EH.app/Contents/MacOS/subprocess EH".

There is no known schedule for CEF Python 51 releases for other platforms as of this moment.

**Comment by mmolero** [comment]
FYI: wxpython.py does not work

```
[wxpython.py] architecture=64-bit
[wxpython.py] wx.version=3.0.0.0 osx-cocoa (classic)
[CEF Python] Initialize() called
[CEF Python] CefExecuteProcess(): exitCode = -1
[CEF Python] CefInitialize()
2016-07-07 17:53:41.511 python[12377:890858] Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
[CEF Python] App_OnBeforeCommandLineProcessing_BrowserProcess()
[CEF Python] Command line string for the browser process:  --browser-subprocess-path=/anaconda/lib/python2.7/site-packages/cefpython3/subprocess --lang=en-US --log-file=/Users/miguel/Downloads/examples/debug.log --log-severity=info --enable-release-dcheck --resources-dir-path=/anaconda/lib/python2.7/site-packages/cefpython3/Resources --remote-debugging-port=54232 --no-sandbox --locale_pak=/anaconda/lib/python2.7/site-packages/cefpython3/Resources/en.lproj/locale.pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
[CEF Python] Switch already set, ignoring: locale_pak
[CEF Python] BrowserProcessHandler_OnBeforeChildProcessLaunch()
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
```

**Comment by cztomczak** [comment]
Google this message: "This program needs access to the screen" - lots of info on the web. Looks like this is not an error, but something that requires configuring Anaconda/wxPython.

Please ask questions on the Forum.

**Comment by kennytm** [comment]
For now, if you must use plugins, you may workaround by symlinking `python2.7/site-packages/cefpython3/subprocess` to `subprocess EH.app/Contents/MacOS/subprocess EH`.

**Comment by cztomczak** [comment]
As explained earlier new CEF doesn't use "EH" helpers, thus the issue does not occur anymore. v56 for Mac will be released today. Closing. If you want to enable Flash in new CEF see Issue #235.
