### ISSUE TITLE
Drag & drop in OSR mode (Kivy). Expose API on all platforms.

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#251]
Drag & drop doesn't work in upstream cefclient on Linux, two related topics on the CEF Forum:
- https://magpcss.org/ceforum/viewtopic.php?f=6&t=14393&p=31801#p31801
- https://magpcss.org/ceforum/viewtopic.php?f=6&t=14464

Two commits in upstream that added d&d support in OSR mode on Windows and Mac:
- In branch 1916: [1] https://bitbucket.org/chromiumembedded/cef/commits/998fa796ca69210baf0072e1141f9fc2c6e0d413?at=1916
- In master: [2] https://bitbucket.org/chromiumembedded/cef/commits/dea4daffd71be5262cf42fa8f3ba6a93d0465c9f?at=master

On Mac drag-image representation is not implemented (upstream [Issue #1715](https://bitbucket.org/chromiumembedded/cef/issues/1715)). On Windows looks like there is drag-image representation (I haven't tested), but from looking at the code it is implemented using Windows API specific functions (probably IE html parser that might not be reliable that much), and such functions are not available on Linux / Mac (d&d OS APIs). 

On Linux there is an issue with d&d in Chrome/cefclient in windowed-mode in the html5demos drag example - the drag-image representation is missing. Looks like this is some issue with that example.

I am testing d&d with these two examples:
- https://mdn.github.io/drag-and-drop/copy-move-DataTransfer.html
- http://html5demos.com/drag

Drag & drop in OSR Kivy was implemented in CEF Python in these commits:
- 7b2b8f5a205440a6d8eec2a7d1ba5307a22b14f8
- 8bd800f2d6f3a73255c5d06925704ac3465276c7
- 21549c7adc36035717e4c71799ccabcc95092d4b

There is still missing the drag-image representation. Currently a custom drag-drop icon is displayed during drag.

In cefclient to implement d&d in OSR on Linux it would be required to use OS d&d functions to register the window as draggable, similarly was done for Win/Mac (links [1], [2] posted at the beginning of the post). Below is a bunch of links on how to do that:
- Drag & drop tutorial from a book: http://www.compsci.hunter.cuny.edu/~sweiss/course_materials/csci493.70/lecture_notes/GTK_dragndrop.pdf
- GTK 2 manual links:
  - https://developer.gnome.org/gtk2/stable/
  - https://developer.gnome.org/gtk2/stable/gtk2-Drag-and-Drop.html
  - https://developer.gnome.org/gtk2/stable/gtk2-Selections.html
  - https://developer.gnome.org/gtk2/stable/gtk2-Signals.html
  - https://developer.gnome.org/gdk2/stable/
  - https://developer.gnome.org/gdk2/stable/gdk2-Drag-and-Drop.html
- Useful sources implementing GTK d&d:
  - https://github.com/LuaDist/wxwidgets/blob/master/src/gtk/dnd.cpp
  - http://www.scintilla.org/ScintillaGTK.cxx

**Comment by cztomczak** [comment]
Drag image representation was added in commit 054a2abcc3b819e8d8a0384acd09a0479ebd9a7a. New patch for CEF was added in the patches/ directory (issue251.patch) that exposes new functions for this feature.

**Comment by cztomczak** [comment]
The drag-image representation patch was sent to upstream through [Pull request #80](https://bitbucket.org/chromiumembedded/cef/pull-requests/80/add-functions-to-support-image/diff).

**Comment by cztomczak** [comment]
Implemented drag & drop in cefclient OSR and have sent patch to upstream via [Pull request #85](https://bitbucket.org/chromiumembedded/cef/pull-requests/85/support-drag-drop-in-cefclient-osr-on/diff).

**Comment by jegger** [comment]
Does the code (of CEF) has to be updated to be merged upstream by Marshall? (because of his feedback / inline comments)

**Comment by cztomczak** [comment]
Yes, comments need to be addressed and PR needs to be updated to supported branch 2924. Marshall also requested creating unit tests for this functionality. I was waiting long time for Marshall's review and then got other things to do, so it got delayed. It's one of my first priorities to take on this after v56 releases, see the "next release" label.

**Comment by cztomczak** [comment]
Windows/Mac releases are using Spotify binaries, so the patch is not applied. Building from sources takes a lot of time on Windows. Right now I'm working on v56 release for Windows with Python 3 support.

**Comment by cztomczak** [comment]
Merging this patch got delayed, as I had to update to latest CEF before sending new pull request. Working on a new pull request now.

**Comment by cztomczak** [comment]
Created new pull request for upstream CEF with added unit tests:
https://github.com/chromiumembedded/cef/pull/2

**Comment by cztomczak** [comment]
New method added to DragData object: GetImageHotspot() in commit af7005e.

**Comment by cztomczak** [comment]
Upstream PR was merged into branch 3071 (v59):
https://bitbucket.org/chromiumembedded/cef/commits/1f2e2bd

**Comment by cztomczak** [comment]
Reopening. This still requires additional changes in CEF Python, currently these new drag methods are exposed only on Linux.

**Comment by cztomczak** [comment]
Upstream PR with drag & drop implementation in cefclient commited in branch 3071 (v59):
https://bitbucket.org/chromiumembedded/cef/commits/ece9353

**Comment by cztomczak** [comment]
Custom patch for this issue removed in f87422b. There are still changes required in cython code and in docs so that the new functions are exposed on all systems.

**Comment by cztomczak** [comment]
DragData image APIs exposed on all platforms in rev c0a8011.
