### ISSUE TITLE
Some commandline invalid

### ISSUE THREAD

**Issue by wrecode** [cztomczak/cefpython#280]
I think this is not this project bug.

example:

appSettings = {}
appSettings["log_severity"] = cef.LOGSEVERITY_DISABLE

commandLineSwitches = {}

# disable-pinch valid
commandLineSwitches["disable-pinch"] = ""

# kiosk invalid
commandLineSwitches["kiosk"] = ""

cef.Initialize(appSettings, commandLineSwitches)

**Comment by cztomczak** [comment]
Please read this:
1. Do not create Issues to report problems and/or ask questions. Use the Forum for that.
2. Before creating an Issue it must first be discussed and confirmed on the Forum.
3. Always use the Forum: https://goo.gl/xz4cEF

**Comment by wrecode** [comment]
sorry

**Comment by cztomczak** [comment]
No problem. I will soon add these guidelines to github CONTRIBUTING file so that it appears when creating an issue.

**Comment by wrecode** [comment]
Thank you, this is a good project. Thanks again.
