### ISSUE TITLE
Windows release of latest v55+

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#294]
This release is part of the sponsorship by [ClearChat, Inc.](https://clearchat.com/). Initial release for Windows will be ready in about a month and will support Python 2.7 and wxPython. Schedule for support of Python 3 and other GUI frameworks on Windows platform, is not available at this time.

**Comment by carlosperate** [comment]
> Schedule for support of Python 3 and other GUI frameworks on Windows platform, is not available at this time.

This makes me a bit sad, but it's completely understandable taking in consideration the mammoth task that is to maintain this project.
Is Python3 support for latest CEF releases on all platforms in the roadmap?

**Comment by cztomczak** [comment]
@carlosperate Yes, see the Python 3 support GH project: https://github.com/cztomczak/cefpython/projects/1

**Comment by carlosperate** [comment]
Awesome, thanks @cztomczak!

**Comment by caodixy** [comment]
hi,could you tell me the release time of  latest v55+?

**Comment by cztomczak** [comment]
Initial Windows support added in commits 7491576 and 60ebfb8. There are still unresolved issues with unittests and examples. Tkinter example launches fine, however it crashes sometimes with error: `Fatal Python error: PyEval_RestoreThread: NULL tstate`. Unit tests fail during browser creation (added option for debugging: `python _test_runner.py --debug`. The hello world example also crashes.

**Comment by cztomczak** [comment]
Issues in unit tests and in examples resolved in commit 97712b3. Tested the following examples: hello_world.py, wxpython.py and unit tests. All works great now. I will still do some more testing to make sure everything works good and will make a release tomorrow (Python 2.7 32-bit only for now).

**Comment by cztomczak** [comment]
All examples do run fine on Windows now after fixes in commit 9bd3acc.

```
OK    hello_world.py
OK    wxpython.py
OK    gtk2.py
OK    qt.py pyqt
OK    qt.py pyside
OK    tkinter_.py
OK    gtk3.py
```

**Comment by cztomczak** [comment]
v55.4 for Windows released: https://github.com/cztomczak/cefpython/releases/tag/v55.4

Command to generate wheel package for current distribution:
`python setup.py bdist_wheel --python-tag cp27`

**Comment by caodixy** [comment]
thanks a lot ! @ cztomczak , i check it and found that devtools can't use, is it a bug?

**Comment by cztomczak** [comment]
@caodixy Created Issue #303

**Comment by cztomczak** [comment]
devtools fixed see https://github.com/cztomczak/cefpython/issues/303#issuecomment-281646458

**Comment by caodixy** [comment]
thanks for your job! @cztomczak , i want to know whether this version supports "window.Notification" , could you tell me? thanks again.

**Comment by cztomczak** [comment]
@caodixy I don't think so. Check it by running.
