### ISSUE TITLE
Windows 64-bit support

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#316]
Fix compiler issues.

**Comment by kunc** [comment]
Hi, sorry to bother you, but I really look forward for the Win 64 bit support, when do you expect next release? Will it include Python 3?

**Comment by cztomczak** [comment]
Working on it right now. v56 release for Windows will support Py3 and both 32-bit and 64-bit platforms. It should happen within days, unless there are issues. So far it looks good.

**Comment by cztomczak** [comment]
Done in commit 	e0ef669.

**Comment by cztomczak** [comment]
v56.0 released: https://github.com/cztomczak/cefpython/releases/tag/v56.0-win
