### ISSUE TITLE
CefPrintDialog and CefFileDialog implementation

### ISSUE THREAD

**Issue by AdrianoPatrizio** [cztomczak/cefpython#319]
I visited the cefpython api documentation and the cef c++ documentation, it would be very usefull implement print and file dialog.

**Comment by cztomczak** [comment]
Please report issues on the Forum.
This is duplicate. Print dialog was implemented in #238. File dialog on Linux is to be implemented in #241.

**Comment by cztomczak** [comment]
File and js dialogs implemented in #241.
