### ISSUE TITLE
Cleanup in PyPI / pip releases

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#329]
A new v56.1 release for Windows / Linux / Mac is being prepared.

Many of v50+ wheels were uploaded to [v31.2 release](https://pypi.python.org/pypi/cefpython3/31.2) on PyPI. This is wrong. A new release must be created before uploading new wheels. When using twine tool this is done automatically. Today I've tried moving 56.0 windows/mac wheels into v56.0 release, however you can't re-upload files that were already uploaded once. So right now the v56.0 wheels are deleted from pypi. Same for v53, v54 and v55 that were uploaded within v31.2 release. GitHub old releases must be updated that they are no more installable using pip.

**Comment by aidos** [comment]
Just to confirm — how are we meant to be installing cefpython3 now? `pip install cefpython3==56.1` isn't working for me (there are no versions of cefpython3 found on pypi.

**Comment by cztomczak** [comment]
@aidos You can install previous releases using packages attached to [GitHub releases](https://github.com/cztomczak/cefpython/releases). v56.1 release wasn't yet published, it will be ready within a few hours.

**Comment by aidos** [comment]
Thanks, that's what I did in the end. I was going to post the issue on the tracker and saw the note about using the google forums then saw your post over there about being in the middle of a release. Will leave you to it :-)

**Comment by cztomczak** [comment]
v56.1 can now be installed using pip.

PyPI release: https://pypi.python.org/pypi/cefpython3/56.1
GitHub frelease: https://github.com/cztomczak/cefpython/releases/tag/v56.1
