### ISSUE TITLE
Version 56.1 in Linux not work

### ISSUE THREAD

**Issue by AdrianoPatrizio** [cztomczak/cefpython#336]
My python script in Linux worked in 55.3 but after last update to 56.1 Browser Window not show anymore. If you want, I post the verbose log, but not crash and not print any error message.

**Comment by cztomczak** [comment]
Please do not submit issues here. Report problems on the Forum. Enable debugging by setting ApplicationSettings "debug", "log_file" and "log_severity" settings and attach debug.log file.
