### ISSUE TITLE
wxPython 4.0 never calls CefApp.OnInit on Mac

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#350]
The `super(CefApp, self).__init__(redirect=redirect)` call never returns and OnInit is never called. This only occurs if cef.Initialize() was called beforehand.  There seem to be two solutions:

1. Initialize CEF after wx was initialized, eg. during a call to embed_browser(). However that results with autorelease error when exiting app.

2. Implement CefApp.OnPreInit and do wx window creation in that event instead of OnInit.

Issue originally reported on the Forum:
https://groups.google.com/d/topic/cefpython/tM8SXp_a_u0/discussion

**Comment by cztomczak** [comment]
Fixed in commit 7c3ffb5. Whether the Solution 2 has any side effects is yet to be discovered.

**Comment by andrewleech** [comment]
Works great for me on both:

[wxpython.py] CEF Python 56.1
[wxpython.py] Python 3.6.1 64bit
[wxpython.py] wxPython 4.0.0a1 osx-cocoa (phoenix)

[wxpython.py] CEF Python 56.1
[wxpython.py] Python 2.7.10 64bit
[wxpython.py] wxPython 4.0.0a1 osx-cocoa (phoenix)

Nice solution, Thanks!

**Comment by cztomczak** [comment]
Regarding autorelease pool error, this may be fixed in CEF v59+. Upstream issue for reference: https://bitbucket.org/chromiumembedded/cef/issues/2160/incorrect-use-of-autorelease-pools-in-3071
