### ISSUE TITLE
Issues with High DPI support in latest CEF on Windows

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#358]
High DPI was last tested by me in the v31 release. There were some changes in upstream CEF in regards to High DPI support. For example in phpdesktop it was no more required to change zoom level according to OS DPI settings.

SetProcessDpiAware code was commented out in phpdesktop:
https://github.com/cztomczak/phpdesktop/blob/c00988f69348b73b6dee27bdf45d145b719e2a3d/phpdesktop-chrome39/dpi_aware.cpp#L14

CEF Python has the same code. It needs to be checked whether this needs to be commented out as well:
https://github.com/cztomczak/cefpython/blob/824d7ce1efacde0a9f0e453cd69325d23fe3e7a9/src/client_handler/dpi_aware.cpp#L163

In the wxpython.py example you can see this code that enables High DPI support:
```
if WINDOWS:
        settings["auto_zooming"] = "system_dpi"  # High DPI support
        # noinspection PyUnresolvedReferences, PyArgumentList
        cef.DpiAware.SetProcessDpiAware()  # Alternative is to embed manifest
```

PHP Desktop embeds DPI aware manifest by default:
https://github.com/cztomczak/phpdesktop/blob/master/phpdesktop-chrome57/DeclareDPIAware.manifest

**Comment by cztomczak** [comment]
In latest CEF v57 there is no need to call `cef.DpiAware.SetProcessDpiAware()`. Actually there are casses when calling it on High DPI devices may break UI in app. On Windows 10 when I've set OS custom scaling to 125% everything worked fine whether `SetProcessDpiAware` was called or not. However when I've set custom scaling to 132% and `SetProcessDpiAware` is called then UI in app becomes broken, everything is much bigger and clicking elements don't work.

There is yet another issue with High DPI. When OS custom scaling is set to a non-standard value like 132% then app UI becomes blurry (images, fonts, everything).

**Comment by cztomczak** [comment]
When custom scaling is set to 132% in Windows 10, calling `cef.DpiAware.SetProcessDpiAware()` will cause the Renderer process to crash, it is then relaunched and crashes again, and so on in a loop. Changing "auto_zooming" option to either "system_dpi" or "" or other fixed values doesn't change anything, it still crashes.

**Comment by cztomczak** [comment]
Fixed in cefpython57 branch in commit 331bfb5 and in master branch in commit ebdb184.

See Migration Guide document for new changes:
https://github.com/cztomczak/cefpython/blob/master/docs/Migration-guide.md#v571-high-dpi-support-on-windows

Both main process and subprocesses are now set to be DPI aware when cef.DpiAware.EnableHighDpiSupport function is called.

Updated wxpython.py example.

**Comment by cormacc** [comment]
Hi - not sure whether to post here or create a new issues, but appear to be encountering a regression in relation to this on cefpython3 66 / Windows 10
Specifically the problem described here in relation to r57, with an unscaled version of the window inlaid/overlaid on the scaled version:
https://magpcss.org/ceforum/viewtopic.php?f=6&t=13659

I'm packaging a python app -- was initially using cefpython3 directly with a window launcher based on the pywin32 example, but now using it via pywebview instead. The problem is evident using either approach.

**Comment by cztomczak** [comment]
@cormacc Does the issue reproduce with the original wxpython.py example? https://github.com/cztomczak/cefpython/blob/master/examples/wxpython.py

It's best to report problems on the forum.

**Comment by cormacc** [comment]
I'm afraid it does. Steps taken to reproduce below, but I'll duplicate them in that forum thread. Or would you prefer I post under a new topic? 

Steps to reproduce:
- git clone https://github.com/cztomczak/cefpython
- cd cefpython/examples
- pipenv shell
- pipenv install cefpython3
- pipenv install wxpython
- python wxpython.py

Laptop is fairly mainstream -- a Thinkpad T580 with the high def screen option, running Windows 10 Pro

**Comment by cztomczak** [comment]
@cztomczak This is issue tracker. Please create a topic on the forum so we can discuss your problem further. Provide more details on your issue. In the referenced CEF topic the reporter said his issue was resolved by adding DPI awareness manifest.

**Comment by cztomczak** [comment]
@cormacc This is issue tracker. Please create a topic on the forum so we can discuss your problem further. Provide more details on your issue. In the referenced CEF topic the reporter said his issue was resolved by adding DPI awareness manifest.
