### ISSUE TITLE
[qt.py] [PySide] Process sometimes hangs when exiting app

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#360]
Problem occurs on both Windows and Mac in the qt.py example running with PySide 1.2. Process hangs when quitting app. This needs further debugging to figure out what call is causing the issue - whether it is cef.Shutdown.

Issue on Windows reported on the Forum ("python.exe" has stopped working):
https://groups.google.com/d/topic/cefpython/PPPqWlRGx-8/discussion

**Comment by raphaelm** [comment]
``self.setAttribute(Qt.WA_DeleteOnClose, True)`` in the ``__init__`` method of the window seems to help

**Comment by cztomczak** [comment]
@raphaelm That makes sense when you take into consideration comment in the qt.py example which says that "app" object must be destroyed before calling cef.Shutdown. So windows objects should be destroyed as well.

**Comment by cztomczak** [comment]
Fixed in PR #409.
