### ISSUE TITLE
 Right Bottom of Image not rendering

### ISSUE THREAD

**Issue by picarro-sgupta** [cztomczak/cefpython#363]
We are using CEFPythonV57 to take the screen shot of the web page. When the page size goes bigger (widthXheight => 4700 X4700 approx) , I am getting this issue.
we are using JavaScript binding to notify python capture code , put some wait time after getting notification before copying the paint buffer. increasing the timer doesn't help.
Any pointers to solve this will be appreciated.
Platform : Linux Red hat, Python 2.7 with dpi 120
![cefpythonissue](https://cloud.githubusercontent.com/assets/7563161/26270944/a5d77af6-3cb4-11e7-9ee8-804de173456d.PNG)

**Comment by cztomczak** [comment]
Please ask questions on the Forum.
