### ISSUE TITLE
can you tell me how to find the example what i need?

### ISSUE THREAD

**Issue by kevzeng** [cztomczak/cefpython#417]
sir
Sorry to disturb you again.
can you tell me how to find the example what i need?  
e.g:  i want to find example about "Frame.GetSource()",and where can i find the example?

**Comment by cztomczak** [comment]
Please do not create issues in the tracker. For help go to Forum.

**Comment by kevzeng** [comment]
sorry , we are not allow to visit google in China.nerver do that again.sorry
