### ISSUE TITLE
CEF v66/v67 official build support when building from sources is provided only for Ubuntu 16.04

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#420]
Starting with current master in CEF, which uses Chromium v66 at the moment, official build support when building CEF from sources is provided only for Ubuntu 16.04. Building with other versions or distros has not been tested and may experience issues.

**Comment by prsolucoes** [comment]
Hi,

If you can, launch a new release with 66/67 source for windows, mac and linux, please.

Thanks.

**Comment by cztomczak** [comment]
Working on that right now.

Ubuntu 14.04 is still supported when using sysroot (Chromium-provided chroot environment). See this topic for details: http://magpcss.org/ceforum/viewtopic.php?f=6&t=15974
