### ISSUE TITLE
OnFileDialog and OnPdfPrintFinished

### ISSUE THREAD

**Issue by qq18436558** [cztomczak/cefpython#421]
https://github.com/qq18436558/cefpython
Update to cef 3.3325.1756.g6d8faa4
Add CefFileDialogCallback
Add CefFastPdfPrintCallback

Test OnFileDialog and OnPdfPrintFinished on Mac and Win10 in wxpython.py

**Comment by cztomczak** [comment]
If you would like to share your code then you should create a pull request. Code will have to be reviewed. Pull requests should implement only one feature at a time. Update to latest CEF is under works and will be ready in the coming weeks.
