### ISSUE TITLE
how can I change proxy ip:port setting without change switches before start in cefpython.

### ISSUE THREAD

**Issue by adams-king** [cztomczak/cefpython#491]
dear, author
    How can I change proxy like use CefRequestContext.SetPreference(proxy_setting_parameter) in cefpython. Are there something like that function in cefpython? please help me, thanks!

**Comment by cztomczak** [comment]
Please ask questions on the Forum. Preferences are not yet implemented in cefpython. Proxy currently can be set only via switch.
