### ISSUE TITLE
icu_util.cc(133)  Invalid file descriptor to ICU data received when used pyinstaller

### ISSUE THREAD

**Issue by buff2017** [cztomczak/cefpython#499]
im use window 10 x64
and
```
 [hello_world.py] CEF Python 66.0
 [hello_world.py] Chromium 66.0.3359.181
 [hello_world.py] CEF 3.3359.1774.gd49d25f
 [hello_world.py] Python 3.7.1 32bit
```

this my .spec file(i thot not related with it)
```
block_cipher = None
a = Analysis(['__main__.py'],
             pathex=["C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\10.0.17763.0\\ucrt\\DLLs\\x86"],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='__main__',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False )
```
i get this when i open pyinstaller builded exe file
`[1219/004030.604:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.`

I tried: [https://github.com/cztomczak/cefpython/blob/master/examples/pyinstaller/README-pyinstaller.md](https://github.com/cztomczak/cefpython/blob/master/examples/pyinstaller/README-pyinstaller.md) step by step , but still get this error

and also , i spend whole day use google search , but still not find solution(actually find out some solution, but that work for Linux or Mac)

i tried lower version Python 3.6.7 but still get this error

i dont know this error is about my computer or dev environment?

**Comment by cztomczak** [comment]
Please ask questions on the Forum.
