### ISSUE TITLE
Not working TAB and RETURN key on wxPython

### ISSUE THREAD

**Issue by parg-programador** [cztomczak/cefpython#508]
My browser navigates and works correctly, but when I try to use the TAB to change the field or the RETURN key simply nothing happens. I looked at other issues and Google to solve this, but nothing worked.

I had the idea to send these keys to the browser when the wx.EVT_CHAR_HOOK event is triggered and with that I managed to solve the problem, I do not know this was the best solution, but it was the one I got, I'll leave it here.

```python
class MyBrowser(wx.Frame):
    def __init__(self):
# ...  more code
        # window events
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_CHAR_HOOK, self.OnKeyEvent)
# ...  more code
    def OnKeyEvent(self, event):
        keycode = event.GetUnicodeKey()

        if keycode == wx.WXK_TAB:
            key_event = {
                "type": cef.KEYEVENT_KEYDOWN,
                "windows_key_code": cef.VK_TAB,
                "character": cef.VK_TAB,
                "unmodified_character": cef.VK_TAB,
                "modifiers": cef.EVENTFLAG_NONE
            }

            page = self.notebook1.GetPage(self.notebook1.GetSelection())
            page.browser.SendKeyEvent(key_event)
        elif keycode == wx.WXK_RETURN:
            key_event = {
                "type": cef.KEYEVENT_CHAR,
                "windows_key_code": cef.VK_RETURN,
                "character": cef.VK_RETURN,
                "unmodified_character": cef.VK_RETURN,
                "modifiers": cef.EVENTFLAG_NONE
            }

            page = self.notebook1.GetPage(self.notebook1.GetSelection())
            page.browser.SendKeyEvent(key_event)
        else:
            event.Skip()
```

If anyone has a better solution I appreciate it.

**Comment by cztomczak** [comment]
This is possibly duplicate of #152. The solution for keyboard issues in wxPython is to remove the wx.TAB_TRAVERSAL style for all parent controls. Fixing it via `wx.EVT_CHAR_HOOK` is another possibility. This is discussed in details in the mentioned issue.

@parg-programador Does removing the wx.TAB_TRAVERSAL resolve the issue for you or do you still need to apply the `wx.EVT_CHAR_HOOK` fix? Also are you setting the `wx.WANTS_CHARS` style on all parent controls?

**Comment by parg-programador** [comment]
I tried to apply the #152 issue solution, but again it gave the same problem.

I applied ```wx.WANTS_CHARS``` to all the parent controls and even then continued the problem.

**Comment by habokuntes** [comment]
Are you sure that you applied the wx.WANTS_CHARS to all parents? I actually found your issue here only because I had the same problem. But for me there was a panel with wx.WANTS_CHARS style missing. I tested now only on Windows but also your event code works for me. But to really look inside some additional information are needed like OS, wxpython version and a minimal full non working source code to see better if there is something missing

**Comment by parg-programador** [comment]
Yes I trying apply in all parents, have only three parents:
--wx.frame
----wx.aui.AuiNotebook
------wx.Panel

Probably it's not working because another routine causing conflict. When I use ```wx.WANTS_CHARS``` and I type RETURN the action of my first menu execute and when I type TAB my menu gain focus.

For create menu I use:
```python
    def create_menu(self):
        mn_arquivo = wx.Menu()
        mm_nova_aba = mn_arquivo.Append(wx.ID_ANY, "New Tab", "Open new tab.")
        mn_arquivo.AppendSeparator()
        mm_fechar = mn_arquivo.Append(wx.ID_EXIT, "Close", "Close the browser.")

        self.Bind(wx.EVT_MENU, self.OnMenuNovaAba, mm_nova_aba)
        self.Bind(wx.EVT_MENU, self.OnMenuFechar, mm_fechar)

        mn_favoritos = wx.Menu()
        mn_favoritos.AppendSeparator()
        mn_gerenciar_favoritos = mn_favoritos.Append(wx.ID_ANY, "Manage Favoritos", "Manage the favorites websites.")
        mn_gerenciar_favoritos.Enable(False)

        menubar = wx.MenuBar()
        menubar.Append(mn_arquivo, "&File")
        menubar.Append(mn_favoritos, "&Favorites")
        self.SetMenuBar(menubar)

    def OnMenuNovaAba(self, event):
        self.notebook1.AddPage(Aba(self.notebook1), "New Tab")
        self.notebook1.SetSelection(self.notebook1.GetPageCount() - 1)
```

**Comment by parg-programador** [comment]
I believe that problem occurs because I using the class ```wx.aui.AuiNotebook```, when I use ```wx.Notebook``` with style ```wx.WANTS_CHARS``` works normaly, but the default class for Notebook it's limited, in this moment I go use my solution with a little modification.

Thanks a lot.

```python
    def OnKeyEvent(self, event):
        keycode = event.GetUnicodeKey()

        if keycode == wx.WXK_TAB:
            key_event = {
                "type": cef.KEYEVENT_KEYDOWN,
                "windows_key_code": cef.VK_TAB,
                "character": cef.VK_TAB,
                "unmodified_character": cef.VK_TAB,
                "modifiers": cef.EVENTFLAG_NONE
            }

            page = self.notebook1.GetPage(self.notebook1.GetSelection())
            page.browser.SendKeyEvent(key_event)
            return
        elif keycode == wx.WXK_RETURN:
            # verifica se o foco está na barra de pesquisa
            if wx.Window.FindFocus().GetId() == self.pesquisa.GetId():
                self.OnPesquisar(None)
                return
            else:
                key_event1 = {
                    "type": cef.KEYEVENT_CHAR,
                    "windows_key_code": cef.VK_RETURN,
                    "character": cef.VK_RETURN,
                    "unmodified_character": cef.VK_RETURN,
                    "modifiers": cef.EVENTFLAG_NONE,
                    "focus_on_editable_field": True,
                    "is_system_key": False
                }

                key_event2 = {
                    "type": cef.KEYEVENT_KEYDOWN,
                    "windows_key_code": cef.VK_RETURN,
                    "character": cef.VK_RETURN,
                    "unmodified_character": cef.VK_RETURN,
                    "modifiers": cef.EVENTFLAG_NONE,
                    "focus_on_editable_field": True,
                    "is_system_key": True
                }

                page = self.notebook1.GetPage(self.notebook1.GetSelection())
                page.browser.SendKeyEvent(key_event1)
                page.browser.SendKeyEvent(key_event2)
                return
        
        event.Skip()
```

**Comment by cztomczak** [comment]
@parg-programador Thanks for the code. I have summarized all possible issues with text input in wxPython in Issue #152 first comment and I have linked to your code for sending key events for this special case.
