### ISSUE TITLE
The bug with wxpython-response.py

### ISSUE THREAD

**Issue by wangbinfei** [cztomczak/cefpython#521]
I tried many times for the wxpython-response.py, but it dose not normally worked.Lastly I firstly wrote "self._data = self._data.encode(encoding='utf8')"  in the method of "OnRequestComplete" when it begin.Sorry, I am Chinese and can every body see what I say?
(I doese not use the wx and I used the cefpython directly.)

**Comment by cztomczak** [comment]
Please ask questions either on the forum or on Stackoverflow tagged 'cefpython'.
