### ISSUE TITLE
Mouse Context Menu dows not show on Linux

### ISSUE THREAD

**Issue by mitras2** [cztomczak/cefpython#524]
The mouse right-click context menu in CEFPython does not show up on my Linux machine any more (which makes it impossible to debug the Web-Frontend).

I have the sneaking suspicion that it might have occured since the time I last updated my system (to GNOME 3.32.1)

My system specs are:
- Python 3.7.3
- CEFPython 66.0
- Manjaro Linux x64  
- GTK 3.24.8-1, GNOME 3.32.1 (Wayland)

The code I use to start CEFPython is basically:
```python
def init_gui():
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    settings = {
        "context_menu": {
            "enabled": True,
            "devtools": True
        }
    }
    cef.Initialize(settings=settings)
    browser = cef.CreateBrowserSync(url=f'file:///{get_html_file_path()}', window_title="KnowLink")
    # browser = cef.CreateBrowserSync(url="localhost:8080", window_title="KnowLink")
    set_javascript_bindings(browser)
    cef.MessageLoop()
    cef.Shutdown()
```
I tried it with and without the custom settings. There is just no context menu showing up (and the shortcuts `F12` or `Ctrl + Shift + i` do not work either to bring up the devtools.

The only message I get in the console when starting the application is:
```
DevTools listening on ws://127.0.0.1:64409/devtools/browser/d24cd661-e092-4724-8bcc-3ebb7ebb584a
[0503/121003.809836:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
```
Could this issue be caused by an update or is there maybe some sort of configuration(-file) for CEFPython that cloud have been changed or deleted accidentally?

**Comment by cztomczak** [comment]
Does it work in hello_world.py example? Does it work in other examples? (wxpython.py, qt.py). You can show Developer Tools popup programmatically by calling `Browser.ShowDevTools`.

**Comment by cztomczak** [comment]
Wayland is currently not supported, see Issue #523.

**Comment by mitras2** [comment]
I did use wayland before the update and the context menu did show as intended.
Probably something about GTK/Wayland has changed...
