### ISSUE TITLE
 Packing with pyinstaller is particularly large

### ISSUE THREAD

**Issue by HuerFu** [cztomczak/cefpython#533]
hello,When I pack it with cefpython, exe is very big. What should I do?Thank you

**Comment by cztomczak** [comment]
I suggest you ask on pyinstaller support channel. It is not recommended to use single exe file option in pyinstaller, as this creates a huge exe that slows down app launching considerably. To trim down executables and DLLs on Windows you can use UPX tool or use a good compression algorithm when creating installer for your app.

**Comment by HuerFu** [comment]
OK，thanks

**Comment by darthglowball** [comment]
I'm using pywebview with cefpython as the browser. I used pyinstaller to create a one folder exe and it is approximately 160 MB (excluding personal resources). Is this a normal size for cefpython?

**Comment by cztomczak** [comment]
CEF Python v66 for Windows 32-bit wheel package is 61 MB in size. This is an archived zip, after extraction it is 144 MB. When creating app installer and using good compression algorithm the size can be reduced to 43 MB.

**Comment by HuerFu** [comment]
I'm also using pywebview with cefpython as the browser. I used pyinstaller to create a exe also 160 MB. i think you have same problem as me. if don't use gui="cef", such as gui="mshtml" , the exe is only 14 MB

**Comment by darthglowball** [comment]
@cztomczak  I'm making an app that only uses javascript and html for the interface & logic, and I don't care about many browser features. Are there settings in cefpython that can exclude certain browser features like search history, cookies, API's, etc. from the frozen app, and would that reduce its size?

**Comment by cztomczak** [comment]
No, there aren't. You can remove some of the files, but this won't reduce the size significantly. If you worry about size don't use CEF (Chrome).

**Comment by darthglowball** [comment]
@cztomczak alright, thank you!
