### ISSUE TITLE
Generate exe by pyinstaller 3.2.1(with wxpython),excute exe on windows ,there is a windows protect message pop up

### ISSUE THREAD

**Issue by Jackjiayou** [cztomczak/cefpython#537]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython
Generate exe by pyinstaller 3.2.1(with wxpython),excute exe on windows ,there is a windows protect message pop pu .
Cloud you help me solve the problem?

below picture can not show ,so I write the message, the message is "windows protected you PC, Windows Detender SmartScreen prevented an unrecognized app from starting,Running this app might put you PC at risk"

![windows_protexcted1](https://user-images.githubusercontent.com/43378246/65005981-5212c780-d934-11e9-8331-b786e156fa9f.png)

**Comment by cztomczak** [comment]
You can sign your executable, so that it becomes trusted. See for example answers here: https://stackoverflow.com/q/48946680

**Comment by Jackjiayou** [comment]
Thanks a lot!
