### ISSUE TITLE
No effect  '--log-file':'disable' 

### ISSUE THREAD

**Issue by 54huige** [cztomczak/cefpython#542]
Here is my code.
I don't know
Why doesn't it work.
`    settings = {
    }

    g_commandLineSwitches={
        "--enable—file-cookies": 'enable',
        '--allow-file-access-from-files':'enable',
        '--allow-insecure-localhost':'enable',
         '--log-severity':'disable',
        '--enable-media-stream':'enable',
        '--log-file':'disable'
        }
        cef.Initialize(settings,g_commandLineSwitches)`

**Comment by cztomczak** [comment]
You cannot pass 'enable' or 'disable', it doesn't work like that. See https://github.com/cztomczak/cefpython/blob/master/api/CommandLineSwitches.md#command-line-switches
To set log file and log severity use ApplicationSettings, see https://github.com/cztomczak/cefpython/blob/master/api/ApplicationSettings.md#log_file
