### ISSUE TITLE
Seperate wheels for seperate python versions.

### ISSUE THREAD

**Issue by momojohobo** [cztomczak/cefpython#548]
In the cefpython3 folder there are 5 binaries for 5 different python versions (from 2.7 to 3.7).
Then in __init__.py there's this:
```
`# Load the cefpython module for given Python version
if sys.version_info[:2] == (2, 7):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py27 as cefpython
elif sys.version_info[:2] == (3, 4):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py34 as cefpython
elif sys.version_info[:2] == (3, 5):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py35 as cefpython
elif sys.version_info[:2] == (3, 6):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py36 as cefpython
elif sys.version_info[:2] == (3, 7):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py37 as cefpython'
to determine which of these binaries to use.
```

The amount of these binaries add up once you have cefpython installed on many virtual environments, and so does their collective file-size. User only needs one of these binaries per environment, and pypi is well equipped handling different python versions.

**Comment by cztomczak** [comment]
What is the size of the wheel package? And what are the sizes of the cefpython modules? Most of the wheel package size will still be CEF binaries which take lots of space. How much the size will be reduced by this change, is it going to be 5% of the wheel package size or so?

**Comment by momojohobo** [comment]
Installed, these binaries are a combined 22.1 MB of 211.6MB. A little over 10%. I am not sure how much wheel compression affects these numbers.

**Comment by cztomczak** [comment]
Saving 10% of space is rather a low priority for me and has some minuses. Currently there are 5 wheel packages available for a release. With this change the number of wheel packages would increase to about 30 files. The total of 30 files to upload during a release would increase to 6 GB. Also it might be useful to have one wheel package and be able to test it on multiple Python versions.

**Comment by momojohobo** [comment]
Another solution could be to make cefpython truly version-agnostic, but something tells me you would have made it so already if it were possible. In any case this would be a separate issue.

**Comment by cztomczak** [comment]
CEF Python wheels are universal, it's a feature. I don't plan on working on this, so closing.
