### ISSUE TITLE
 How to set data to a Navigator object

### ISSUE THREAD

**Issue by Delfinys** [cztomczak/cefpython#553]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython

Hello, please show me an example of how to set the necessary properties for the browser navigator object such as Navigator.Platform, Navigator.hardwareConcurrency, Navigator.doNotTrack ..... and others

**Comment by Delfinys** [comment]
I re-read everything and tried it but did not find a working method or the right answer - please give the most complete answer - I am writing from Linux 64 - in python

**Comment by cztomczak** [comment]
You can overwrite js objects by executing custom javascript with Browser/Frame.ExecuteJavascript() function. It's best to do it in the LoadHandler.OnLoadStart callback. For example to overwrite navigtor.platform property use such code:
```js
Object.defineProperty(navigator, 'platform', {
    get: function() {
      // Keep it simple and just return Windows id for all platforms.
      return 'Win32';
    }
  });
```

**Comment by Delfinys** [comment]
can show a complete example?



# Hello world example. Doesn't depend on any third party GUI framework.
# Tested with CEF Python v57.0+.

from cefpython3 import cefpython as cef
import platform
import sys


def main():
    check_versions()
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    cef.Initialize()
    cef.CreateBrowserSync(url="https://www.google.com/",
                          window_title="Hello World!")
    cef.MessageLoop()
    cef.Shutdown()


def check_versions():
    ver = cef.GetVersion()
    print("[hello_world.py] CEF Python {ver}".format(ver=ver["version"]))
    print("[hello_world.py] Chromium {ver}".format(ver=ver["chrome_version"]))
    print("[hello_world.py] CEF {ver}".format(ver=ver["cef_version"]))
    print("[hello_world.py] Python {ver} {arch}".format(
           ver=platform.python_version(),
           arch=platform.architecture()[0]))
    assert cef.__version__ >= "57.0", "CEF Python v57.0+ required to run this"


if __name__ == '__main__':
    main()

**Comment by cztomczak** [comment]
You can use the ondomready.py snippet as a base. Just modify the javascript in OnLoadStart: https://github.com/cztomczak/cefpython/blob/master/examples/snippets/ondomready.py

**Comment by Delfinys** [comment]
Thank you very much, you helped a lot in resolving my issue. Good luck and have a nice day!
