### ISSUE TITLE
Shared libraries in manylinux1 wheel should not be linked against libpythonX.Y.so.1.0

### ISSUE THREAD

**Issue by el-dee** [cztomczak/cefpython#554]
In the cefpython wheel for manylinux1 platform, the shared libraries cefpython_pyXY.so are linked against the corresponding libpythonX.Y.so.1.0

This is against manylinux recommendations that extension modules should not be directly linked against a given version of the lib python but instead should use the symbols exported by the interpreter or the application that loaded the extension (see, https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1)

Doing otherwise makes the extension module unusable for application that are using a different version of the interpreter or are statically linked against the Python interpreter (which by definition are not shipped with a libpythonX.Y.so.1.0) For the latter case, providing an empty libpythonX.Y shared library can be a workaround and proves that cefpython3.cefpython_pyXY.so does not need its own libpython.

**Comment by cztomczak** [comment]
> providing an empty libpythonX.Y shared library can be a workaround and proves that cefpython3.cefpython_pyXY.so does not need its own libpython.

It may break some packages that depend on dlopen, although the discussions on the web suggest it is a rare case. I think it needs testing before making it the default.

On Python 3.8 it is now the default to not link to libpython on Unix (except for Android and Cygwin). 
Ref:
1. https://github.com/python/cpython/blob/master/Doc/whatsnew/3.8.rst#debug-build-uses-the-same-abi-as-release-build
2. https://bugs.python.org/issue21536

When building cefpython module on Ubuntu system Python 2.7.6 then the module is not linked to libpython. From what I've read on the web Debian/Ubuntu Python extensions in 99% cases don't link to libpython.

Created branch `Issue-554` and commited a fix via a1510a4844dfd23791b7597efe40f68258422f0c. Please test.

**Comment by rdb** [comment]
@cztomczak What system are the Linux wheels built on?  If I use `auditwheel show` on the manylinux1-tagged wheel, it appears to be linked with a much more recent version of glibc than manylinux1 allows, suggesting it does not actually satisfy the requirements of the manylinux1 platform tag.

If you build the wheels on the official manylinux1 docker container, these problems should be resolved.

**Comment by cztomczak** [comment]
@rdb cefpython package includes CEF/Chromium binaries and I'm afraid it will never satisfy manylinux1 recommendations. Currently CEF requires glibc >= 2.14.

**Comment by cztomczak** [comment]
Building on Ubuntu 14.04 / 16.04.

**Comment by cztomczak** [comment]
Should run out of the box on Debian 8+, Ubuntu 14.04+, Fedora 24+, openSUSE 13.3+.

**Comment by cztomczak** [comment]
Fix for "m" suffix in python library name in commit 33c546b.

**Comment by cztomczak** [comment]
Merged via PR #557.
