### ISSUE TITLE
Set Proxy python

### ISSUE THREAD

**Issue by Delfinys** [cztomczak/cefpython#555]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython

Hello, I can’t install a proxy, the browser displays a white background and loads nothing

    switches={

      "proxy-server": "login:password@ip:port",

    }
    sys.excepthook = cef.ExceptHook
    cef.Initialize(settings={}, switches=switches)

Please tell me how to make the browser work through a proxy

Development goes on Linyx -> python3

And I also wanted to immediately ask you to send links to WebRtc, WebGl emulation examples, Plug-in substitution, audio context, etc.

**Comment by cztomczak** [comment]
Please ask questions on the forum

**Comment by Delfinys** [comment]
But how do I install a proxy--Отправлено из мобильной Яндекс.Почты12.01.2020, 01:29, "Czarek Tomczak" <notifications@github.com>:Closed #555.

**Comment by Delfinys** [comment]
The presented design does not work, as for the rest, I understood. Tell me how to install a proxy
