### ISSUE TITLE
Pyinstaller convert tkinter_.py to exe error

### ISSUE THREAD

**Issue by noval102200** [cztomczak/cefpython#563]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython
When i use Pyinstaller to convert  tkinter_.py in examples folder to exe.
It run errors as below happened:
[tkinter_.py] CEF Python 66.0
[tkinter_.py] Python 3.6.4rc1 32bit
[tkinter_.py] Tk 8.6.6
[0310/140708.938:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.

But the script is run ok on python interpreter.
What's the reason maybe?

**Comment by cztomczak** [comment]
Do not create issues in the tracker.
