### ISSUE TITLE
How to call CreateBrowserSync in a UI thread?

### ISSUE THREAD

**Issue by wekay102200** [cztomczak/cefpython#565]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython
When i niitialize cef with settings below :
cef.Initialize(settings={'multi_threaded_message_loop':True})
then it throw message below:
cefpython.CreateBrowserSync() may only be called on the UI thread

How can i call CreateBrowserSync in a UI thread?

**Comment by cztomczak** [comment]
Do not create issues in the tracker. Use forum.
