### ISSUE TITLE
Webpage not show when access the webserver which security certificate is not trusted.

### ISSUE THREAD

**Issue by yickowang** [cztomczak/cefpython#566]
My user have a webserver ,https://xxx.xxx.xxx:3000,  but the webserver's security certificate is not trusted,and when i visit the webserver through chrome,the page will show a warning and i can still visit by 'process to  xxx.xxx.xxx.xxx' link.see the picture below.
![abc](https://user-images.githubusercontent.com/40831103/76375958-0b050c80-6382-11ea-8787-01565b8e48a9.jpg)

but when i use the cefpython visit the website ,the page is blank(white screen),the code is the helloworld.py.see the picture below.

![222](https://user-images.githubusercontent.com/40831103/76376034-3d166e80-6382-11ea-940d-a8d0e5096e4e.png)
i don't know how to deal with this situation,would u please give me some suggestion?

**Comment by cztomczak** [comment]
Pass ApplicationSettings.ignore_certification_errors option to cef.Initialize. See https://github.com/cztomczak/cefpython/blob/master/api/ApplicationSettings.md#ignore_certificate_errors .

**Comment by yickowang** [comment]
Set the option, it's work ok.Thank you!
