### ISSUE TITLE
Strange behavior when using wxpython + cefpython + pyinstaller

### ISSUE THREAD

**Issue by marcelomanzo** [cztomczak/cefpython#571]
Hello,

I was to sucessful integrate my application using wxpython + cefpython, everything is working properly when I launch it from python myscript.py
 

![image](https://user-images.githubusercontent.com/12878783/79080484-4b3e0e80-7ce3-11ea-9fab-17fb51972838.png)

But I pack it using pyinstaller, it works, but when I click on any link this what happens with the screen, the same dos not happen when I call from python myscript.py neither on chrome, only when I call the exe created by pyinstaller:

![image](https://user-images.githubusercontent.com/12878783/79080476-3d888900-7ce3-11ea-8433-95d28f7e5472.png)

Any suggestion to debug is welcome... 

Thanks a lot!

**Comment by cztomczak** [comment]
Already answered on forum.
