### ISSUE TITLE
A dummy Python script with complete CEF Python API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#58]
See also Issue #204 - Generate API documentation from Cython sources. This will help to auto generate and also document all functions.

Such a dummy Python script was available in CEF 1. It provides code completion in IDE and can act as a quick reference for all functions. See it here:
https://github.com/cztomczak/cefpython/blob/c05fcf28665ad521c575d2944933acdda260c46b/cefpython/cef1_api.py

The dir() function could be used to automate generation of such file.  

```
from cefpython3 import cefpython
dir(cefpython)
```

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 25 May 2013 at 7:38

**Comment by cztomczak** [comment]
PyCharm generates such stub for cefpython module. Use Pycharm.
