### ISSUE TITLE
Does cefpython provide a bridge for python classes to be used by JS?

### ISSUE THREAD

**Issue by rlaPHOENiX** [cztomczak/cefpython#580]
For example:

Within python script:
```py
class DataStorage:
  def __init__(self):
    self.stored_list = []
  def store(self, data):
    self.stored_list.append(data)

UsernameDataStorage = DataStorage()
UsernameDataStorage.store("rla")
...
# Pass to javascript land somehow?
```

Within javascript console:
```js
window.UsernameDataStorage.store("PHOENiX")
window.UsernameDataStorage.stored_list  // should have: ["rla", "PHOENiX"]
```

After that, back in the Python script:
```py
UsernameDataStorage.stored_list  # should have: ["rla", "PHOENiX"] (be up to date)
```

The expected result is it to store that value in both JS lands pointer as well as pythons pointer, the data should be available and updated on both JS and Python side. Once stored, it should be able to retrieve the list.

This would make a lot of great possibilities if this was possible, surely there's a way that I haven't spotted?

**Comment by cztomczak** [comment]
CEF Python allows for asynchronous communication between js and python, both ways. Since its asynchronous data must be returned via callbacks mechanism. See https://github.com/cztomczak/cefpython/blob/master/docs/Tutorial.md#javascript-integration
For simple example see javascript_bindings.py snippet in examples/snippets/.

**Comment by rlaPHOENiX** [comment]
> CEF Python allows for asynchronous communication between js and python, both ways. Since its asynchronous data must be returned via callbacks mechanism. See https://github.com/cztomczak/cefpython/blob/master/docs/Tutorial.md#javascript-integration
> For simple example see javascript_bindings.py snippet in examples/snippets/.

Right my bad, I totally forgot the Objects js bind, I was trying to use it via Properties :rofl:
