### ISSUE TITLE
URL not correct when forwarded

### ISSUE THREAD

**Issue by nabeelio** [cztomczak/cefpython#587]
Hello,

I'm using the `OnLoadEnd()` callback; I am trying to use a PKCE auth scheme, and it forwards to a callback address with some information. However, the URL being reported by the dev-tools is correct, but for both the browser and frame `GetUrl()` calls, it's being reported as `chrome-error://chromewebdata`, I'm not sure why - there's no errors showing up in the dev console or anything either.

Is this a bug or am I just using this wrong?

Thanks!

![image](https://user-images.githubusercontent.com/99736/95374199-0a970a80-08ac-11eb-898c-3857c743d820.png)

**Comment by cztomczak** [comment]
Can you create a simple snippet that reproduces the issue?

**Comment by nabeelio** [comment]
Yup, I'm hosting 2 simple pages. It seems like it happens on a forward but the page is an error 

```python
from cefpython3 import cefpython as cef
import platform
import sys


def main():
    check_versions()
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    cef.Initialize()
    browser = cef.CreateBrowserSync(url="http://li1271-24.members.linode.com/page1.php",
                          window_title="Hello World!")

    browser.SetClientHandler(LoadHandler())
    cef.MessageLoop()
    cef.Shutdown()


def check_versions():
    ver = cef.GetVersion()
    print("[hello_world.py] CEF Python {ver}".format(ver=ver["version"]))
    print("[hello_world.py] Chromium {ver}".format(ver=ver["chrome_version"]))
    print("[hello_world.py] CEF {ver}".format(ver=ver["cef_version"]))
    print("[hello_world.py] Python {ver} {arch}".format(
            ver=platform.python_version(),
            arch=platform.architecture()[0]))
    assert cef.__version__ >= "57.0", "CEF Python v57.0+ required to run this"


class LoadHandler(object):
    """ """
    def OnLoadEnd(self, browser, frame, http_code):
        """

        :param browser:
        :param frame:
        :param http_code:
        :return:
        """
        # Dump all of the cookies
        print(f"OnLoadEnd: url={browser.GetUrl()}")
        print(f"OnLoadEnd: frame ={frame.GetUrl()}")
        print(f"OnLoadEnd: http_code={http_code}")


if __name__ == '__main__':
    main()

```
![image](https://user-images.githubusercontent.com/99736/95376052-82663480-08ae-11eb-82e5-cdcf84ce2692.png)

**Comment by cztomczak** [comment]
Is LoadHandler::OnLoadError callback called? What if you do just one redirect? What if you use http for localhost? What if you pass "disable-web-security": "" switch to cef.Initialize? (not secure to use this option if you load third party websites). What if you ignore certificate errors (since you use self signed cert on localhost): https://github.com/cztomczak/cefpython/blob/master/api/ApplicationSettings.md#ignore_certificate_errors . Is your localhost web server actually running and can you load it in cefpython?

Maybe there are some security headers set on localhost causing this? See https://github.com/cypress-io/cypress/issues/4220#issuecomment-661676579

**Comment by nabeelio** [comment]
Obviously this is just a sample but all the certs, etc are fine, the redirect is going to/coming back from Okta, so no difference there, in my little demo as well, with turning down the security. The first redirect is just to simulate the login form being filled out. 

So I didn't realize there was an `OnLoadError` callback, so I added that and `OnLoadingStateChange()`

```python
def OnLoadingStateChange(self, browser, is_loading, **_):
    print(f"OnLoadingStateChange: url={browser.GetUrl()}")

def OnLoadError(self, browser, frame, error_code, error_text_out, failed_url):
    """ """
    print(f"OnLoadError: browser url={browser.GetUrl()}")
    print(f"OnLoadError: frame url={frame.GetUrl()}")
    print(f"OnLoadError: error_code={error_code}")
    print(f"OnLoadError: error_text_out={error_text_out}")
    print(f"OnLoadError: failed_url={failed_url}")
```

And it returns:

```
OnLoadingStateChange: url=
OnLoadError: browser url=
OnLoadError: frame url=
OnLoadError: error_code=-102
OnLoadError: error_text_out=['ERR_CONNECTION_REFUSED']
OnLoadError: failed_url=https://localhost/code=asdflkj&scope=abc
OnLoadEnd: url=chrome-error://chromewebdata/
OnLoadEnd: frame =chrome-error://chromewebdata/
OnLoadEnd: http_code=0
```

That's interesting with the URL being returned as blank in all 3 callbacks (I don't think would be correct?), but I guess that's Chrome doing that? The URL in DevTools shows it being correct, though. I can workaround it for now, though, with using the `failed_url` for what I need, but that's kinda yucky.

Is that the expected behavior with an invalid URL? I could see someone else having this issue too if they were to use it for PKCE or something like that where they're trying to use an oauth workflow, since the callback is supposed to be something like "localhost" and there won't necessarily be anything hosted there (like for an app, or something)

**Comment by cztomczak** [comment]
When url fails to load chrome will change url to `chrome-error://chromewebdata/`. See https://source.chromium.org/search?q=kUnreachableWebDataURL&ss=chromium

**Comment by nabeelio** [comment]
Makes sense, thanks, I guess I was expecting the `OnLoadingStateChange` or something to have the URL which it had to forward to, but I can work with this. Thanks for your help! I'll close this.
