### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by Berserker66** [cztomczak/cefpython#593]
It is properly released now. So, continuation issue of https://github.com/cztomczak/cefpython/issues/546

**Comment by cztomczak** [comment]
New v66.1 release for Windows with Python 3.8 / 3.9 support is ready: https://github.com/cztomczak/cefpython/releases/tag/v66.1

**Comment by snehccurry** [comment]
@cztomczak I've tried building an exe, it throws an exception saying no module named json was found, even the exe that you have included doesn't seem to work, even the exe throws the same error, please help, I've been stuck on this for a year now, can you make a youtube video on this please? cuz the steps are really confusing to me as a beginner. would be really thankful to you sir.
