### ISSUE TITLE
Error running the exe which was built using pyinstaller

### ISSUE THREAD

**Issue by praveenp2004** [cztomczak/cefpython#598]
I got an error after running an exe which was built using pyinstaller

The error :- " ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received. "

modules i imported:
- cefpython
- sys
- json
- platform

**Comment by cztomczak** [comment]
CEF binaries seem to be missing. There is a pyinstaller example in the repository.

**Comment by nnnewb** [comment]
same problem here.

python version: 3.7.9 AMD64
pyinstaller version: 4.1
cefpython3 version: 66
packaging by command line: `pyinstaller --clean --win-private-assemblies --noupx -c -n cracker .\winmain.py`

**Comment by cztomczak** [comment]
There is an example hook for pyinstaller. See PR#600.
