### ISSUE TITLE
Errors when building CEF Python hello_world.py with Pyinstaller

### ISSUE THREAD

**Issue by Correct-Syntax** [cztomczak/cefpython#605]
**Setup:**
windows 10
python 3.8
cefpython v66.1
pyinstaller 4.2

I was attempting to build the ``hello_world.py`` **(unmodified)** with pyinstaller. The application builds into /dist/ just fine, however once I try to run the exe it has errors.

The first time, I kept getting an error about ``ModuleNotFoundError: No module named 'json'[5188] Failed to execute script hello_world`` with just ``pyinstaller hello_world.py``.

Then, I changed the pyinstaller commands to be:
```
pyinstaller -n "Test" --hidden-import json "hello_world.py"
```

When I ran the exe it had the output:
```
[hello_world.py] CEF Python 66.1
[hello_world.py] Chromium 66.0.3359.181
[hello_world.py] CEF 3.3359.1774.gd49d25f
[hello_world.py] Python 3.8.6 64bit
[0216/154928.922:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
```

**Comment by cztomczak** [comment]
There is a pyinstaller example in the examples/ directory.

**Comment by Correct-Syntax** [comment]
Must I use pyinstaller==3.2.1 in order for it to work?

**Comment by cztomczak** [comment]
No. It should work fine with latest pyinstaller 4.x. Use the example from master branch.

**Comment by Correct-Syntax** [comment]
Taking a closer look, the error shown at https://github.com/cztomczak/cefpython/blob/master/examples/pyinstaller/README-pyinstaller.md#debug-app is pretty similar to mine. How do I fix this?

Thank you.

**Comment by cztomczak** [comment]
You would need to add a dependency manually. See "hiddenimports" here: https://github.com/cztomczak/cefpython/blob/d2c72528addad8ef41a2a460946f32fe425ed183/examples/pyinstaller/hook-cefpython3.py#L198

**Comment by Correct-Syntax** [comment]
I see. I will try that. Thanks for the help!

**Comment by Correct-Syntax** [comment]
Hmmm....

```
[hello_world.py] CEF Python 66.1
[hello_world.py] Chromium 66.0.3359.181
[hello_world.py] CEF 3.3359.1774.gd49d25f
[hello_world.py] Python 3.8.6 64bit
[0216/154928.922:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
```

**Comment by cztomczak** [comment]
It seems pyinstaller didn't copy the icudtl.dat file.
This should be included in the "datas": https://github.com/cztomczak/cefpython/blob/d2c72528addad8ef41a2a460946f32fe425ed183/examples/pyinstaller/hook-cefpython3.py#L238

**Comment by Correct-Syntax** [comment]
I've been addiing this to the pyinstaller ``.spec`` file. I'm not sure it's possible to add ``get_cefpython3_datas() `` directly into the .spec.

**Comment by Correct-Syntax** [comment]
Sorry if I missed this, but was I suppose to include the hook-cefpython.py?
