### ISSUE TITLE
Rendering issues with Nvidia GeForce 30-series GPUs

### ISSUE THREAD

**Issue by buck54321** [cztomczak/cefpython#612]
[Here's a short video](https://imgur.com/a/eNRyw5E) to demonstrate. That's just a single div with the word hello. Cannot interact, and when you do, a smaller picture-in-picture type sub-window is displayed. The developer tools window has the same thing going on.

Problem is fixed with `commandLineSwitches={"disable-gpu": True}`. 

[Others are experiencing issues with the 30 -series and CEF as well, apparently.](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/269933/cef-chromium-embedded-framework-incompatibility-af/)

I'd guess there's little you can do about this. Feel free to use as a tracking issue, but mostly I just wanted to save others some time if they experience similar issues.

Windows 10 Home laptop. Nvidia GeForce 3070, 465.89 driver

**Comment by cztomczak** [comment]
This sounds like DPI awareness issue, see https://github.com/cztomczak/cefpython/issues/530

**Comment by buck54321** [comment]
Ah. Missed that. Thank you.
