### ISSUE TITLE
kivy example bug for windows

### ISSUE THREAD

**Issue by fernancode** [cztomczak/cefpython#613]
Hi,

I was trying out the kivy example on my windows machine and was getting no luck running it (I was getting a "_event.pyx" does not exist), until a stackoverflow user advised me to change 
`self.browser_widget() = CefBrowser(id='browser')` to just 
`self.browser_widget() = CefBrowser()`
and it worked.

My understanding of kivy is not strong enough to know why this allowed it to work, but per the s.o. reply, "It is that kivy uses the kwargs to handle the bindings (events) but the event or property "id" does not exist, so it throws that error." Just wanted to share this and thanks for the great work on cefpython

**Comment by fernancode** [comment]
line #47 by the way in kivy example. thanks :)

**Comment by cztomczak** [comment]
Thanks. Fixed in commit 431b9956db660d5552c31fb4a3a891f619ed84a8.
