### ISSUE TITLE
LD_LIBRARY_PATH overwritten by cefpython

### ISSUE THREAD

**Issue by hoba87** [cztomczak/cefpython#614]
After loading cefpython on Linux, the LD_LIBRARY_PATH is overwritten and only contains the cefpython path.

**Comment by cztomczak** [comment]
Here is the recent change in v66.1: https://github.com/cztomczak/cefpython/commit/019033d2919a4fab84cb832ec5b76aad12e39c40

Do you see an error there?

**Comment by cztomczak** [comment]
A comment says that a better solution would be to use `-Wl,-rpath=\$$ORIGIN` in Makefile instead of overwriting that env variable.

**Comment by cztomczak** [comment]
PR is welcome.

**Comment by cztomczak** [comment]
Oh wait, I was too fast. That commit actually fixed the issue you're reporting. So you just need to build from master.

**Comment by hoba87** [comment]
Ah ok, thank you. A release of 66.1 also for Linux would be welcome.
