### ISSUE TITLE
GetResourceHandler doesn't fire in v66, v66.1 (In v57.1 it works fine)

### ISSUE THREAD

**Issue by KindYAK** [cztomczak/cefpython#616]
I am trying to use a custom ClientHandler on my browser:

main.py:
```
from cefpython3 import cefpython as cef
import sys
import os
import tempfile

from browser.handlers import ClientHandler

def main():
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    settings = {
        "context_menu": {
            "enabled": False
        },
        "downloads_enabled": False,
        "cache_path": tempfile.gettempdir(),
        "debug": False,
        "log_file": tempfile.gettempdir() + os.sep + "log.txt",
        "remote_debugging_port": 3777,
    }
    url = os.path.join(os.getcwd(), "index.html")
    cef.Initialize(settings=settings)

    browser_settings = {
        "file_access_from_file_urls_allowed": True,
        "local_storage_disabled": True,
        "web_security_disabled": True
    }

    browser = cef.CreateBrowserSync(
        url=url,
        window_title="Test",
        settings=browser_settings
    )
    clientHandler = ClientHandler()
    clientHandler.mainBrowser = browser
    browser.SetClientHandler(clientHandler)

    cef.MessageLoop()
    cef.Shutdown()

```

browser.handlers:
```
class ClientHandler:
    # RequestHandler.GetResourceHandler()
    def GetResourceHandler(self, browser, frame, request):
        print("FIRE")
        return None
```

I use Python 3.6.8, Windows 10 (64-bit). When I install cefpython3==57.1 it works (I see "FIRE" in the console), however when I try to install cefpython3==66 or cefpython3==66.1 it stops firing.

I have read the Migration Guide, however I haven't found anything relevant.

**Comment by KindYAK** [comment]
I have researched the problem a bit - the Handler doesn't work only on the initial page. If I go to another page via a link, the Handlers start firing

**Comment by cztomczak** [comment]
Looks like the problem is that browser is created synchronously and handler is registered after the browser created. How about creating an initial browser with `about:blank` url and then calling `LoadUrl` to change it?

**Comment by KindYAK** [comment]
@cztomczak Thank you, sounds like a nice workaround.
I just got confused, because the behaviour changed in respect to version 57.1

**Comment by cztomczak** [comment]
It might be a timing issue. Maybe in newer Chromium things start up faster and thus issue started appearing.

**Comment by cztomczak** [comment]
Just to add to change the url after handler was registered.

**Comment by KindYAK** [comment]
Yep, seems like it.
@cztomczak Thank you for the help!
Seems like it's not actually an issue, so I close it
