### ISSUE TITLE
data decoding problem in WebRequestClient

### ISSUE THREAD

**Issue by Reskayoi** [cztomczak/cefpython#620]
I tried this example in [wxpython-response.py](https://github.com/cztomczak/cefpython/blob/cefpython31/cefpython/cef3/linux/binaries_64bit/wxpython-response.py) and found it works well with python2. 
But in python3, all images and some other reponse data seems break.

After some check，I found this problem seems to be caused by the data transmission method in `web_request.pyx`, it always decoding data into string but images cannot be correctly decoded.

Example:
```
Python 3.9.4 (tags/v3.9.4:1f2e308) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a=b"\x89\x50"
>>> a
b'\x89P'
>>> b=a.decode(errors="replace")
>>> b
'�P'
>>> c=b.encode(errors="replace")
>>> c
b'\xef\xbf\xbdP'
>>>
```

I try to change WebRequestClient_OnDownloadData in web_request.pyx like this:
```python
cdef public void WebRequestClient_OnDownloadData(
 ...
            if userCallback:
                userCallback(
                        web_request=webRequest,
                        data=<bytes>((<char*>data)[:dataLength])) #transfrom bytes
...
```
It seems work well.
Sorry for my poor English.

**Comment by cztomczak** [comment]
Currently the documentation states that the `data` is a string and it should be changed to bytes. So in the code it should call `VoidPtrToBytes` instead of  `VoidPtrToString`. Basically as in your new code. PR is welcome.

```cython
cdef bytes VoidPtrToBytes(const void* data, size_t dataLength):
    return <bytes>((<char*>data)[:dataLength])
```

**Comment by cztomczak** [comment]
Fixed in master.
