### ISSUE TITLE
Python version not supported: 3.11.5

### ISSUE THREAD

**Issue by zhengquantao** [cztomczak/cefpython#670]
Traceback (most recent call last):
  File "D:\project\mini_tool_v2\test.py", line 11, in <module>
    from cefpython3 import cefpython as cef
  File "D:\python\Lib\site-packages\cefpython3\__init__.py", line 64, in <module>
    raise Exception("Python version not supported: " + sys.version)
Exception: Python version not supported: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

**Comment by mithravasan** [comment]
the cefpython3 module does not support Python version 3.11.5. To resolve this issue, you can try one of the following solutions:

Downgrade Python version: You can downgrade your Python version to a version that is supported by cefpython3. To do this, you can use a version manager like pyenv or conda to manage multiple Python versions on your system.

Use a different module: If downgrading Python is not an option, you can look for an alternative module that provides similar functionality and is compatible with your Python version.

Contact the maintainers: You can also consider contacting the maintainers of cefpython3 and requesting support for your Python version. You can open an issue on their GitHub repository or send them an email to bring this to their attention.

Install pyenv
Once you have pyenv installed, use the following command to install the Python version that you need
After the installation is complete, use the following command to set the Python version for your project
Verify that the correct Python version is being used by running:
After downgrading your Python version, you should be able to import the cefpython3 module without encountering the error.

If you have any further questions or issues, please let me know. I'm here to help!

**Comment by mithravasan** [comment]
if your using anaconda software on the amd processor then laptop or pc will not support because it need high configuration
.It happened to me in laptop

**Comment by zhengquantao** [comment]
thanks
