### ISSUE TITLE
Example of integrating Google Breakpad for crash reporting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#70]
Google Breakpad is a multi-platform crash reporting system:
https://code.google.com/p/google-breakpad/

Breakpad is integrated with CEF in branch 1750 and upper. See upstream CEF Issue 1131:
https://code.google.com/p/chromiumembedded/issues/detail?id=1131

See also this CEF topic and Marshall's response:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=10839

> Breakpad needs to be integrated in your application executable and has 
> nothing to do with CEF specifically. In the case of the message you're 
> referencing it's integrated in the chrome_dll and chrome_exe targets (in
> other words, the Chrome browser executable).

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 29 Jun 2013 at 4:49

**Comment by cztomczak** [comment]
Closing in favor of #389.
